### ISSUE TITLE
TA Feedback - 4/26/18

### ISSUE THREAD

**Issue by JoannaRumbley** [attendanceproject/djattendance#1093]
Priority Key
HP = High Priority
MP = Medium Priority

**Leave Slips:**

- [ ] **MP** TA's are unable to change the events on a pending leave slip this should be editable for them  (They cannot change events on group slips. Else, everything is good) @joeyu23 
_Update: Group slips have time block (editable start and end times they can type in). But cannot click/unclick events. Thus, the priority was changed to MP_

- [ ] **MP** When TA's process a leave slip from the detailed view it moves them on to the next leave slip in their queue which is good. However, when they process the last leave slip left in their queue it has a pop up saying saved and just refreshes them on the same page for that leave slip. Instead they should be redirected back out to the summary page and no popup is needed. @joeyu23 

- [ ] **MP** Numerous night out leave slips being reported as disappearing or moving to the following week on its own. Example: Connor Robinson, Samuel Gutierrez, Nestor Zepeda. 
_PM to check with Jerome_

- [ ] Consider possibility of including TA private comments on list view. @yipingbenjaminliu #1139

- [ ] Add attendance period column on leave slip list - TA view. @yipingbenjaminliu #1139
 
- [ ] TA leave slip detailed view - change fields to Trainee, Reason, Description, TA Comments, TA Informed, TA Assigned, and Private TA Comments. 
_Update: Can't do for group slips until time block can be removed. Working on prerequisited fix for group leave slip detailed view (the selected events)_

- [ ] Saving a leave slip on the _detailed_ view does not progress to the next pending leave slip. @AngeloBelmonte

- [ ] When processing leave slips via the detailed view, it would be good to have it automatically ordered so that we process the leave slips dated the earliest first (not the date submitted, but the date the leave slip is for). We had this on the old attendance server. @AngeloBelmonte

- [ ] Trainees are able to indicate a Saturday helper as a TA informed, which is fine. However, if they do so, it creates an error where it assigns the leave slip to him. When a trainee then tries to open the leave slip up, it forces them back to the homepage. When a TA tries to approve it, the page times out and gets a 504 error. Example: http://10.0.8.35/leaveslips/individual/update/2044. I think this is related to the prior issue of leave slips being assigned to non-TAs. 
_Already fixed? PM check live server_

- [ ] When a TA inputs attendance for a trainee, the update is not reflected on the trainee's account (i.e., switching identity). Example: Katya Becker on 4/21 from afternoon study to evening study roll out. Also Emily Hu's attendance from Weeks 0-8. She still has a notification telling her to finalize attendance
_explain how to TAs_

- [ ] TA input attendance - Unclear if clicking "Finalize" does anything. (Maybe have a "Finalized" notification or make the "Finalized" button grayed out.) On the old server, the button blacks out when attendance is finalized. 

- [ ] **MP** There are discrepancies on attendance records between viewing a leave slip (TA detailed view) and viewing a summary. Example: http://10.0.8.35/leaveslips/individual/update/6047 does not show a tardy for 4/29 team fellowship, but when you open up Jeffrey Cheung's personal attendance, a tardy shows. May be related to the Attendance bug that affected Katya and Emily (above). @yipingbenjaminliu 

**Extra field:**
  - [ ] “Does not affect perfect attendance will be a built-in leave slip category” (Automatic for Conferences, team trips, house meals, service, fellowship, and allow for TA override) @AngeloBelmonte

- [ ] Add functionality to "sign out" of Monday dinner via leave slip. 

**AUDIO**
- [ ] Request to add a notation saying that any files approved for download must be deleted? @francestsenn

**GROUP LEAVE SLIPS**

- [ ] When opening up a group leave slip the events do not have the hashed out selected appearance if there is already something there. We need the hashed appearance on the event to show what the group leave slip is for. @joeyu23 

- [ ] Unable to tell who originally submitted a group leave slip. @joeyu23 

**ROLLS:**
- [ ] Add force page when submitting attendance late. 
_clarify with TAs_

- [ ] Add save and finalize buttons for personal, house, and team roll entry (even if it is a dummy finalize and save that does nothing since they automatically save). @yipingbenjaminliu 

- [ ] Need unfinalize roll button. Relatedly, the finalize button should be blanked out if attendance is finalized. @yipingbenjaminliu 

- [ ] TAs do not have a way to input team and house attendance. We currently have to go to each individual trainee. @yipingbenjaminliu 

**Web Access Requests:**

- [ ] No way to unmark a request once you have selected marked for fellowship. Needs to be a way to unmark for fellowship to be consistent with site (also noticed on other modules, such as Web Access) @kcmin

**ROOM RESERVATIONS:**

- [ ] Marking a request for fellowship removes the request from the list. You have to remove "pending" from the search box and type in "fellowship" or "marked for fellowship". This is too cumbersome and confusing. The list should not be based on a search for "pending". Are there any other modules set up like this? 
_@designers_

- [ ] Updating/editing a trainee's room reservation request approves it @zioninzion

**TA Landing Page**
- [ ] TA's should see their personal number of items as well as a total number of items. Ex. web access requests 5 (390). The only exception is leave slips which should only show the TA's personal number of slips @iamsitting 

- [ ] Number of pending requests on TA ***and trainee*** homepages do not match actual number of requests. (Okay we fixed this but the thing is now when they select pending from the home page it actual looks for all sister approved and pending slips which is a good thing but our number is inaccurate again. For the homepage number we need to include slips with TA sister approved status @samvictor232 

**TA List Views**

- [ ] The order of the leave slips on the list view should not be by submission date. They
should be ordered by date of leave slip event, starting with the earliest. 

- [ ] On the summary page ("View Trainee Attendance"), the submitted column on the left is extremely confusing. I thought for the longest time it was referring to the event. Please replace it with some sort of tag that just shows if it was submitted late

- [ ] **MP** On the leave slips summary list page, any filters we ask for are lost and default after we process a single leave slip. The filters should be kept

- [ ] All TA list views need the following sort order (Pending, Marked for Fellowship, Approve, Deny) to stop them from having to excessively scroll. Secondary sort needs to be time submitted based

- [ ] For Leave Slip TA list view Add attendance period column on list view.

- [ ] Across site lists need delete options for items from TA list view

**ABSENTEE TRAINEE ROSTER**
- [ ] Pluses are not being noted on the absent trainee roster. Pluses indicate that there is a possibility the trainee has been absent for more days, but cannot be confirmed due to HCs not submitting a daily accountability form @billyeh @finben 
_Check Kaylin Wiseman's. Marked absent for 5/5 once, but it shows 8+. How is this being counted?_

- [ ] Just tried editing an approved group leave slip, but took me to a 500 error page. Example: http://10.0.8.35/leaveslips/group/update/4224, but not unique to this leave slip. @davidhtien 

**LIFE STUDIES**

- [ ] **HP** Fix assign discipline based on attendance @samvictor232 

- [ ] For the “Assign Discipline” function for attendance the dates along with the period needs to be shown @samvictor232 

**REPORTS**

- [ ] **MP** Generate grade and attendance reports by gospel team and sending locality. @ksungreborn 

- [ ] **HP** The reports generated and printable for Life-study assignments is incorrect need to meet with Andrew for requirements @samvictor232 

**PERMISSIONS**

- [ ] **MP** Saturday helper brothers cannot approve web access requests getting a forbidden error. May affect other modules. @billyeh 

- [ ] Give certain trainees the ability to upload the class files, e.g., ministry meeting verses for PSRP, etc. ( These would be the sisters with the "Special Projects (Outlines)" designated service.) 
_need more details_

**BIBLE READING TRACKER**

**EXAMS:**

- [ ] Once a trainee went on to view the exam (for questions, to start on their exam, etc), it did not allow them to log back on to continue/finish their exam. I believe the workaround for this was to go in and give a trainee “make up exam” privileges.  As of this evening, there were at least 3 trainees that approached me to indicate they weren’t able to log back on to their exams to complete it. @ksungreborn 

**SURVEYS:**
- [ ] Need a way to show which houses actually submitted the HC survey and which houses did not. Currently, if the HCs do not open the page, they do not show up on the report page, and if the HCs open the survey page, it will list them on the report page even without submitting the survey.  - Note: It looks like some houses have not submitted the survey, and it is past the deadline. Needs to be fixed and reopened for those houses to take survey. @yipingbenjaminliu @iamsitting 

- [ ] No organization on HC survey report. Should list all the houses by brothers then sisters. Also, couples do not need to submit surveys, so they should be removed from inputting and the reports. @yipingbenjaminliu @iamsitting 

- [ ] **MP** HC Survey TA's are looking for a way to edit what the survey asks, edit times, and delete the server @yipingbenjaminliu @iamsitting 

**Other:**

- [ ] **MP**Button to change attendance period is only one-pixel large on Firefox. Also not intuitive. @francestsenn 

- [ ] Link for TA's to edit HC survey needs to be more intuitive. @bdou 

- [ ] We now need to start working on a gospel statistics module @iamsitting @ksungreborn 

- [ ] House Requests, Room Reservations, Life Studies, Class notes, are user (Trainee or TA) specific. 
_need clarification_

- [ ] Have a way to take attendance and assign discipline for missed services, rotational or designated. @samvictor232 

- [ ] TAs need to be able to submit new personal or group leave slips on behalf of trainees. @yipingbenjaminliu 

- [ ] **HP** Ensure class notes report page is working after resolving roll/leaveslip issue @yipingbenjaminliu @bdou 

- [ ] 504 Gateway Time-out error when trying to pull up all leave slips for all TAs, even when limiting to 25 slips per page #1025 @yipingbenjaminliu @davidhtien @iamsitting @billyeh 

_____________________________________
**COMPLETE** 😁 🥇 
----------------------------------------

- [x] **Critical Issue:** The calendar no longer shows when pulling up a detailed leave slip view. @billyeh @yipingbenjaminliu 

- [x] **MP** There is an inherent issue with how roll and leave slip entries are being shown on the detailed leave slip page. There is no way to tell visually if there is an absence or tardy "under" a leave slip. Right now any approved leave slip changes the color of the event to blue, whether there is anything marked under or not. Please follow the principle of what we had in the old attendance server 

- [x] Meal cleanup leave slips also excusing trainees from the meals themselves. Not an issue with the start time of the leave slip.

- [x] "View leave slips for" on list view includes people who are not TAs. #1065 

- [x] The word counting feature only worked for the first essay question @ksungreborn 

- [x] Trainees can finalize their Bible reading without making inputs for all of the days. Example: Mark Fan week 6 /JR - Also see related issue #1011 fbbc0bd912e5ad116a1523b177d4587e23789c65

- [x] TA Assigned to this leave slip" has a whole bunch of people who are non-TAs. #1065 

- [x] Allow trainees to access previous Leave slips. Maybe a ListView for trainees.
_Update: Trainees can click on slip from Personal Attendance - Summary and it brings them to their leave slip details under the Personal or Group Slips tab_

- [x] Allow trainees to access previous Leave slips. Maybe a ListView for trainees.
_Update: Trainees can click on slip from Personal Attendance - Summary and it brings them to their leave slip details under the Personal or Group Slips tab_

**Comment by joeyu23** [comment]
@JoannaRumbley In the meantime, the TAs should be able to edit group leaveslips with time ranges

**Comment by JoannaRumbley** [comment]
This was split up into its categories. Please refer to the issue you're tagged in. Hope it makes things easier.

**Comment by JoannaRumbley** [comment]
Leave Slips:
#1140 

Extra Fields:
#1141 

Audio:
#1142 

Group Slips:
#1143 

Rolls:
#1144 

Absentee Trainee Roster:
#1145 

Life Studies:
#1146 

Reports:
#1147 

Permissions:
#1148 

Exams:
#1149 

Web Access Requests:
#1150 

Room Reservations;
#1151 

TA Landing Page:
#1152 

TA List Views:
#1153 

Other:
#1154
