### ISSUE TITLE
TA Feedback - Leave Slips

### ISSUE THREAD

**Issue by JoannaRumbley** [attendanceproject/djattendance#1140]
**Leave slips:**

- [ ] Trainee submitted a group leave slip (#7132), but the start and end time on the left side on the detailed view does not match with the event highlighted on the calendar (Lord's Day lights out)

- [ ] When a TA inputs attendance for a trainee, the update is not reflected on the trainee's account (i.e., switching identity). Example: Katya Becker on 4/21 from afternoon study to evening study roll out. Also Emily Hu's attendance from Weeks 0-8. She still has a notification telling her to finalize attendance
_explain how to TAs_
- [ ] **MP** There are discrepancies on attendance records between viewing a leave slip (TA detailed view) and viewing a summary. Example: http://10.0.8.35/leaveslips/individual/update/6047 does not show a tardy for 4/29 team fellowship, but when you open up Jeffrey Cheung's personal attendance, a tardy shows. May be related to the Attendance bug that affected Katya and Emily (above). @yipingbenjaminliu 
- [x] **MP** Numerous night out leave slips being reported as disappearing or moving to the following week on its own. Example: Connor Robinson, Samuel Gutierrez, Nestor Zepeda. 
_PM to check with Jerome_ | Did we figure this out? -david

- [x] Consider possibility of including TA private comments on list view. @yipingbenjaminliu #1139

- [x] Add attendance period column on leave slip list - TA view. @yipingbenjaminliu #1139
 
- [x] TA leave slip detailed view - change fields to Trainee, Reason, Description, TA Comments, TA Informed, TA Assigned, and Private TA Comments. 
_Update: Can't do for group slips until time block can be removed. Working on prerequisited fix for group leave slip detailed view (the selected events)_ @finben #1166

- [x] **MP** When TA's process a leave slip from the detailed view it moves them on to the next leave slip in their queue which is good. However, when they process the last leave slip left in their queue it has a pop up saying saved and just refreshes them on the same page for that leave slip. Instead they should be redirected back out to the summary page and no popup is needed. @joeyu23 #1200 

- [x] **MP** After clicking a button on the detailed view, it takes 10 seconds for it to go on to the next leave slip. This is too slow to be practical. / Update: We are receiving increased reports about delays looking up and processing leave slips, especially the day after attendance office hours. Increased priority to MP #1200 
- [x] The submitted late tag is not showing up on the detailed view of a leave slip but only on the TA list view. I think we had this working before and when I roll back about a week worth of commits it works on my dev environment but not on production. Maybe a result of (#1176)? -ben   @davidhtien #1200 
- [x] When processing leave slips via the detailed view, it would be good to have it automatically ordered so that we process the leave slips dated the earliest first (not the date submitted, but the date the leave slip is for). We had this on the old attendance server. #1200 

- [ ] TA input attendance - Unclear if clicking "Finalize" does anything. (Maybe have a "Finalized" notification or make the "Finalized" button grayed out.) On the old server, the button blacks out when attendance is finalized. 

- [ ] TAs need to be able to submit new personal or group leave slips on behalf of trainees without having to go into a trainee's attendance.
_Can we put a "Create New Slip" button right under "Select all" on the TA Leave Slip List page? Then it'll direct them to a page that looks like the detailed leave slip page, but the form and calendar are blank._

- [ ] "View leave slips for" on list view includes people who are not TAs. I think this is fixed now - david
@davidhtien Sorry, the detailed view also needs this change under **"Training Office Informed"** Also for **"TA Assigned"**

- [x] Delete function does not seem to be working. #1212

**Comment by finben** [comment]
Moving remaining issues to #1282
