### ISSUE TITLE
TA Feedback - Group Slips

### ISSUE THREAD

**Issue by JoannaRumbley** [attendanceproject/djattendance#1143]
**GROUP LEAVE SLIPS**

- [ ] **MP** TA's are unable to change the events on a pending leave slip this should be editable for them  (They cannot change events on group slips. Else, everything is good) @joeyu23 
_Update: Group slips have time block (editable start and end times they can type in). But cannot click/unclick events. Thus, the priority was changed to MP_

- [x] When opening up a group leave slip the events do not have the hashed out selected appearance if there is already something there. We need the hashed appearance on the event to show what the group leave slip is for. @joeyu23 #1124 

- [x] Unable to tell who originally submitted a group leave slip. @davidhtien #1212 
_@davidhtien This is fixed, but now the calendar on group slips (detailed page) looks broken... 😦_ 
should be fixed now - david

- [x] Just tried editing an approved group leave slip, but took me to a 500 error page. Example: http://10.0.8.35/leaveslips/group/update/4224, but not unique to this leave slip. @davidhtien #1229

**Comment by davidhtien** [comment]
@joeyu23 it seems the first two checkboxes are done now? Can you confirm and maybe edit the comment with the PR numbers?

**Comment by joeyu23** [comment]
@davidhtien Updated the second task. The first checkbox is still yet to be done. The TAs eventually want to be able to edit events, not just by timeblock.

**Comment by finben** [comment]
Moving remaining issues to #1282
