### ISSUE TITLE
TA Feedback - Rolls

### ISSUE THREAD

**Issue by JoannaRumbley** [attendanceproject/djattendance#1144]
**ATTENDANCE/ROLLS:**

- [ ] Need options to unapprove, undeny, unmark for fellowship, unfinalize, etc. Buttons should be "grayed-out" if already approved, finalized, etc. Make grayed-out buttons "unselectable" both on list and detail views. (if the list view has multiple slips selected with different statuses, then the bulk-approve button should make all of them approved. No need to have a bulk-unapprove button.)

- [ ] Add force page when submitting attendance late. 

- [ ] Add save and finalize buttons for personal, house, and team roll entry (even if it is a dummy finalize and save that does nothing since they automatically save). @yipingbenjaminliu #1179 
_...This is not done for house or team roll yet. Br. Jerome says, "I have mentioned before how I do not like how they are "live" entries and different from the other methods of input." So, I think they prefer that it does not auto-save. I'll unmark this since it isn't done. And this is still Low Priority._

- [x] When a TA inputs attendance for a trainee, the update is not reflected on the trainee's account (i.e., switching identity). #1228 

- [ ] Need unfinalize roll button. Relatedly, the finalize button should be blanked out if attendance is finalized. @yipingbenjaminliu #1179 
_I also don't see an Unfinalize button...is it done, but not on the live server yet?_

- [x] TAs do not have a way to input team and house attendance. We currently have to go to each individual trainee. #1228

**Comment by yipingbenjaminliu** [comment]
#1179 should address all the issue here

**Comment by finben** [comment]
Moving remaining issues to #1282
