### ISSUE TITLE
TA Feedback - TA List Views

### ISSUE THREAD

**Issue by JoannaRumbley** [attendanceproject/djattendance#1153]
**TA List Views**

- [x] Across site lists need delete options for items from TA list view
    - [x] Leave Slips #1184
    - [ ] Web Access
    - Any others?

- [x] The "Submitted Late" tag isn't showing on the detailed view, even though it shows on the list view. Let's make it consistent by putting the "Submitted Late" tag on detailed view as well

- [ ] The order of the leave slips on the list view should not be by submission date. They should be ordered by date of leave slip event, starting with the earliest. #1176
@davidhtien I mentioned this in #1140 also: isn't the order backwards? - Joanna
_____________
COMPLETE:

- [x] On the summary page ("View Trainee Attendance"), the submitted column on the left is extremely confusing. I (Jerome) thought for the longest time it was referring to the event. Please replace it with some sort of tag that just shows if it was submitted late #1184
- [x] MP On the leave slips summary list page, any filters we ask for are lost and default after we process a single leave slip. The filters should be kept #1139
- [x] All TA list views need the following sort order (Pending, Marked for Fellowship, Approve, Deny) to stop them from having to excessively scroll. Secondary sort needs to be time submitted based
_I think being able to select the type (pending, fellowship, etc.) solves this. David Tien: Yes, I agree this should be fixed. _
- [x] For Leave Slip TA list view Add attendance period column on list view. #1139
- [x] Include private TA comments on the TA list view. Discuss with designers to know where they want the field added

**Comment by davidhtien** [comment]
@JoannaRumbley do you think the TA's want a bulk delete option?

**Comment by JoannaRumbley** [comment]
Is "delete" different from "deny"?
TAs can approve or deny multiple slips at once. I assume it's the same with web access requests

**Comment by yipingbenjaminliu** [comment]
yes, delete is different from deny. When they deny a request/leaveslip, the object still remains on record. When they delete it, it's gone and there's no trace of it on any records anymore.

**Comment by JoannaRumbley** [comment]
I'll ask the TAs about the bulk delete option

**Comment by JoannaRumbley** [comment]
They don't need a bulk delete option. 

Should I keep this issue here or move it, since it's for other modules too (like all the requests - web access, maintenance, etc)?

**Comment by JoannaRumbley** [comment]
Closing this issue since it overlaps with #1140 
(They're both for leave slips)
