### ISSUE TITLE
Service Week Issues - TA Feedback List 6/23

### ISSUE THREAD

**Issue by finben** [attendanceproject/djattendance#1282]
To give everyone some ideas of things to do for service week. Here is an updated list of bugs from brother Jerome. This list is by no means all inclusive but it is up to date. Overall this has been a successful term and for all of your encouragement in TA bugs alone we have solved 103 bugs total so far into this term. Many big fires have been put out this term and it has been an 'exciting' shakedown cruise. As an additional main objective for this service week we will attempt to upgrade three things.  Our server version, Python to Python 3, and Django to 2.0. this service week. Happy Service Week! -Ben

**Attendance Rolls**
- [ ] Add force page when submitting attendance late.
- [ ] Need unfinalize roll button. Relatedly, the finalize button should be blanked out if attendance is finalized. @yipingbenjaminliu #1179
I also don't see an unfinalize button...is it done, but not on the live server yet?
- [ ] TA input attendance - Unclear if clicking "Finalize" does anything. (Maybe have a "Finalized" notification or make the "Finalized" button grayed out.) On the old server, the button blacks out when attendance is finalized.

**Extra Fields**
- [ ]  Add "Does not count against perfect attendance" check box and functionality. 
- [ ] Does not affect perfect attendance will be a built-in leave slip category” (Automatic for Conferences, team trips, house meals, service, fellowship, and allow for TA override)

**HC Survey List**
- [ ] List should be organized among brother's and sister's houses. Currently no order to the list

**Interim Intensions**
- [ ] On the interim intentions report, for some trainees the "Intention" reads a mix of blanks, "None," and "Serve Full-time: College Campus in the U.S." "Serve Full-time" is not an option for trainees to select under "Returning" on the form. It is only happening to some, not all, the returning trainees (see Adolfo Fernandez, Alejandra Ferrel, and Alex Cantu). The "Intention" for all returning trainees should all read "None."
- [ ] The form on the old attendance server asked for specific information from the trainees based on which option they chose under Post Training Intentions (which translates into "Intentions" on the report in the new server), and not just "Explain:". Most trainees did not provide information such as the locality they will end up in for work, what school and program they will be enrolled in, what campuses they will be serving at, or when they will start serving.

**Leave Slips - Group Slips**
- [ ] TA's are unable to change the events on a pending leave slip this should be editable for them (They cannot change events on group slips. Else, everything is good) @joeyu23
Update: Group slips have time block (editable start and end times they can type in). But cannot click/unclick events. Thus, the priority was changed to MP

**Leave Slips**
- [ ] TA's need to be able to submit new personal or group leave slips on behalf of trainee's without switching to the trainee's name. Automatically approve when the TA submits
- [ ] Applies to both personal and group slips: Delete function of slips does not seem to be working for TA's @davidhtien
- [ ] Issue of multiple leave slips for the same roll call cancelling one another. For example, I approve a leave slip for a roll call, but the attendance does not reflect the approval because there is another leave slip for the same roll call that was not processed or denied. @davidhtien
- [ ] When a leave slip is marked for fellowship have a note of who marked the leave slip for fellowship, so the trainee knows who to go to. 
- [ ] Saving a leave slip on the detailed view does not progress to the next pending leave slip. @davidhtien
- [ ] For TA Sisters, they need a single button for the sisters to approve and transfer. / JR - from Monday meeting: Have different buttons to "Save," "Transfer," and "Approve & Transfer" Currently approve is not transferring them @bdou

**Leave Slip - TA List View**
- [ ] All should be sorted by the earliest event time. When their are multiple events on a slip it should sort by the earliest event on the slip

**Life Studies**
- [ ] The reports generated and printable for Life-study assignments is incorrect need to meet with Andrew for requirements 
- [x] Tried to assign a LS summary. Tells us to put in a valid date and time even though a due date was inputted. @samvictor232 5bd38f0045bb0d554551fb41637f2940b5b7c840
- [ ] When a TA is assigning a life study manually they should be able to select multiple trainee's similar to selecting many on group leave slip. @berlyseria 

**Room Reservations**
- [ ] Marking a request for fellowship removes the request from the list. You have to remove "pending" from the search box and type in "fellowship" or "marked for fellowship". This is too cumbersome and confusing 79b8efd (#1296) @ruthnan
- [ ] I marked a room reservation for fellowship, but there is no indication on the trainee side to see me for fellowship. See Piano Service/Ryan Li/06/23/2018 request. 422245c (#1296) @ruthnan
- [x] When attempting to edit a room reservation, the date for the start and end times change to the year 1900. See http://10.0.8.35/room_reservations/update/144. Actually, the dates should be removed from the start and end times; we already ask for the date on a separate field. 

**Web Access Requests**
- [ ] No way to unmark a request once you have selected marked for fellowship. Needs to be a way to unmark for fellowship to be consistent with site (also noticed on other modules, such as Web Access) @kcmin

**Absentee Trainee Roster**
- [ ] When submitting the daily HC attendance, some HCs are reporting that the system is saying that attendance was already submitted, even though they have not. This is causing a lot of confusion and misunderstanding between the HCs, who said they thought someone already submitted the daily attendance, and the office, who receives the report saying no attendance was submitted.
- [x] Change email send time to 8:30 @finben

**TA Landing Page**
- [x] Add personal number and total number for Life Studies and class notes @samvictor232

**Other**
- [ ] Trainee's added to designated services are not automatically given links to input designated service hours @ruthnan
- [ ] Add a way to take attendance and assign discipline for missed services, rotational, or designated #1131 @samvictor232
- [ ] For Maintenance - Change/Add columns to: date requested, trainee requested, trainee Phone, house, room, request type, description, comments, status. @priscilagonzalez #1293 
- [ ] Date formatting on TA leave slip list view should match the format on the requests tables. Update: For all requests: Have "May 05" format on summary lists and "MM/DD/YY 00:00 AM" format on detail views @priscilagonzalez #1293 
- [x] Entire module missing. Need functionality to input study locations, assign study groups, and input study attendance. @iamsitting #1283 
- [ ] Add a force page for designated attendance service hours @kcmin 
- [ ] The color contrast of a TA comment, in addition to the notes on meal sign-outs and service scheduling, on a leave slip as seen by a trainee is poor. @finben

**Comment by finben** [comment]
Issues have been moved to #1381
