### ISSUE TITLE
Pre-Term Goals

### ISSUE THREAD

**Issue by iamsitting** [attendanceproject/djattendance#1321]
- [x] Fix Travis (#1320, #1322) - Carlos
- [x] Merge APImport #653 - Carlos & Ryan
- [x] Room Reservations (migrate reservations) -Zion
- [x] Merge Rolls Finalization #1281  - Carlos
- [x] TA Sister Status #1125 - Angelo
- [x] Schedule Changes doc (see #1306) - Ryan & Angelo
- [x] Generate CSV file for attendance report (#1234) - Angelo & Zion
- [x] URLS: Zion
  - Give TAs audit view
  - Give AMs Trainee Information Table
  - Disable Semi-annual study location/attendance
- [x] Roll Finalization Announcement - Bridget #1330 
- [x] Fix No group slips for week 0 - Carlos
_____
_____
_____
- [x] Bring back the total numbers for TA cards #1333 
- [ ] ~~Let's update python packages - Angelo~~
- [ ] ~~Let's start using Greenkeeper (#909) - Zion~~
