### ISSUE TITLE
TA Bug Request List -- Aug 27

### ISSUE THREAD

**Issue by finben** [attendanceproject/djattendance#1381]
**Announcements**
- [ ] Need a field informing us if the trainee fellowshiped with and received approval from a TA. @finben #1386 

- [ ] For TA announcements view. Sort list with the most recent requests (based on date of announcement, not date/time of request made) at the top. @finben  #1386 

**Attendance Rolls**
- [ ] Add force page when submitting attendance late. @yipingbenjaminliu
- [x] Input attendance - Unclear if clicking "Finalize" does anything. (Maybe have a "Finalized" notification or make the "Finalized" button grayed out.) On the old server, the button blacks out when attendance is finalized. #1389 

**Extra Fields**
- [ ]  Add "Does not count against perfect attendance" check box and functionality. 
- [ ] Does not affect perfect attendance will be a built-in leave slip category” (Automatic for Conferences, team trips, house meals, service, fellowship, and allow for TA override**

**House Inspections**
- [ ] There is a request that we now need a house inspection module on the new server. Some inspectors are still using the old server.

**HC Survey List**
- [x] List should be organized among brother's and sister's houses. Currently no order to the list @finben

**Interim Intensions**
- [ ] On the interim intentions report, for some trainees the "Intention" reads a mix of blanks, "None," and "Serve Full-time: College Campus in the U.S." "Serve Full-time" is not an option for trainees to select under "Returning" on the form. It is only happening to some, not all, the returning trainees (see Adolfo Fernandez, Alejandra Ferrel, and Alex Cantu). The "Intention" for all returning trainees should all read "None."
- [ ] The form on the old attendance server asked for specific information from the trainees based on which option they chose under Post Training Intentions (which translates into "Intentions" on the report in the new server), and not just "Explain:". Most trainees did not provide information such as the locality they will end up in for work, what school and program they will be enrolled in, what campuses they will be serving at, or when they will start serving.

**Leave Slips - Group Slips**
- [ ] TA's are unable to change the events on a pending leave slip this should be editable for them (They cannot change events on group slips. Else, everything is good)
Update: Group slips have time block (editable start and end times they can type in). But cannot click/unclick events. Thus, the priority was changed to MP

**Leave Slips**
- [ ] TA's need to be able to submit new personal or group leave slips on behalf of trainee's without switching to the trainee's name. Automatically approve when the TA submits
- [x] Applies to both personal and group slips: Delete function of slips does not seem to be working for TA's
- [ ] Issue of multiple leave slips for the same roll call cancelling one another. For example, I approve a leave slip for a roll call, but the attendance does not reflect the approval because there is another leave slip for the same roll call that was not processed or denied. 
- [ ] When a leave slip is marked for fellowship have a note of who marked the leave slip for fellowship, so the trainee knows who to go to. 
- [ ] Saving a leave slip on the detailed view does not progress to the next pending leave slip.
- [ ] For TA Sisters, they need a single button for the sisters to approve and transfer. / JR - from Monday meeting: Have different buttons to "Save," "Transfer," and "Approve & Transfer" Currently approve is not transferring them

**Leave Slip - TA List View**
- [ ] All should be sorted by the earliest event time. When their are multiple events on a slip it should sort by the earliest event on the slip

**Life Studies**
- [ ] The reports generated and printable for Life-study assignments is incorrect need to meet with Andrew for requirements 
- [ ] When a TA is assigning a life study manually they should be able to select multiple trainee's similar to selecting many on group leave slip. @berlyseria 
- [ ] Need functionality to transfer discipline already assigned from one trainee to another.

**Room Reservations**
- [x] Make the "Reason" field required only for trainee accounts. @kcmin
- [ ] There are two date fields on the page that creates room reservations. Per discussion from meeting we should hide the entire date that is on the top of the table. @kcmin
- [ ] Need a way to print schedules. Right now many things are cut off.
- [ ] When inputting times, you can either use the drop-down menu or type it in. However, if you don't type in a type on the half-hours (e.g., :00, :30), approving the room reservation request is not reflected on the schedule. For example, I approved a request for 6:15-6:35, and nothing showed on the schedule. It would be better to remove the option to type the time in since the schedule is based on every 30 minutes. @kcmin
- [ ] When Jerome approves a room reservation request for a room/time that has a conflict, there is no prompt indicating that there was a conflict, giving the impression that the request went through. (This is causing double bookings, **HIGH PRIORITY**). @kcmin @ryanli633 
- [ ] Freeze the "Time Slots" column on http://10.0.8.35/room_reservations/schedule so that it continues to show when scrolling horizontally.
**Web Access Requests**
- [ ] No way to unmark a request once you have selected marked for fellowship. Needs to be
a way to unmark for fellowship to be consistent with site (also noticed on other modules,
such as Web Access) 

**Semi Annual**
- [ ] Merge semi-annual study location and semi-annual study attendance pages. Include functionality to for TA to approve or deny alternate study location requests, and to change study location assignment.
      
**TA Landing Page**
- [ ] On the TA homepage, there are currently two numbers next to "Room Reservations" and "Announcements". As these are not tied to TAs, they can just be shown as one number without any number in parentheses, and in red if there are any pending. @finben

**Other**
- [ ] Trainee's added to designated services are not automatically given links to input designated service hours @ruthnan
- [ ] Add a way to take attendance and assign discipline for missed services, rotational, or designated #1131 @samvictor232
- [ ] For Maintenance - Change/Add columns to: date requested, trainee requested, trainee Phone, house, room, request type, description, comments, status. 
- [ ] Date formatting on TA leave slip list view should match the format on the requests tables. Update: For all requests: Have "May 05" format on summary lists and "MM/DD/YY 00:00 AM" format on detail views
- [ ] Add a force page for designated attendance service hours
- [ ] The color contrast of a TA comment, in addition to the notes on meal sign-outs and service scheduling, on a leave slip as seen by a trainee is poor. @finben
- [ ] Build a Gospel Statistics Module

**Comment by JoannaRumbley** [comment]
Moved to #1397
