### ISSUE TITLE
TA Issue List - Oct 20

### ISSUE THREAD

**Issue by finben** [attendanceproject/djattendance#1464]
**Attendance Rolls**
- [ ] Add force page when submitting attendance late. 

**Class Notes**
- [x] Unable to see what classes (or any other details) of the class notes assigned.

**Extra Fields**
- [x]  Add "Does not count against perfect attendance" check box and functionality. @joysyu 
- [ ] Does not affect perfect attendance will be a built-in leave slip category” (Automatic for Conferences, team trips, house meals, service, fellowship, and allow for TA override**) @joysyu 

**Gospel Trips**
- [x] When revisiting an application and resubmitting an error on the top of the page tells trainees that they need to enter a valid passport expiration date. However, there is no issue with the date.
- [ ]  Trainees report getting a blank page after trying to submit (specifically we believe this is tied to Chrome browser)

**Interim Intentions** ( @bdou )
- [x] On the interim intentions report, for some trainees the "Intention" reads a mix of blanks, "None," and "Serve Full-time: College Campus in the U.S." "Serve Full-time" is not an option for trainees to select under "Returning" on the form. It is only happening to some, not all, the returning trainees (see Adolfo Fernandez, Alejandra Ferrel, and Alex Cantu). The "Intention" for all returning trainees should all read "None."
- [x] The form on the old attendance server asked for specific information from the trainees based on which option they chose under Post Training Intentions (which translates into "Intentions" on the report in the new server), and not just "Explain:". Most trainees did not provide information such as the locality they will end up in for work, what school and program they will be enrolled in, what campuses they will be serving at, or when they will start serving.
- [x] Needs calendar report. See old server 

**Leave Slips** 
- [ ] TA's need to be able to submit new personal or group leave slips on behalf of trainee's without switching to the trainee's name. Automatically approve when the TA submits. _Maybe add a button on the TA Leave Slips List page that leads to a blank "Detail" page. Assign a new leaveslip ID and set Training office informed to Yes._
- [ ] **Critical** Issue of multiple leave slips for the same roll call cancelling one another. For example, I approve a leave slip for a roll call, but the attendance does not reflect the approval because there is another leave slip for the same roll call that was not processed or denied. 
- [ ] When a leave slip is marked for fellowship have a note of who marked the leave slip for fellowship, so the trainee knows who to go to. (We need to visit this along with the bigger idea of a messaging module)
- [x] There is no filter to pull up denied leave slips.
- [ ] There are still issues with how the attendance server processes leave slips for the same roll call(s). Example: Celine Goh submitted four leave slips for Lord's Day curfew and/or lights out for 9/23. One was approved. However, when you pull up any of the other three leave slips, the roll call still shows the absences.
- [ ] When pulling up a leave slip, the calendar only shows the absences and tardies for that leave slip. We would like to see the trainees' complete attendance. In other words, when viewing the weekly calendar, the trainee attendance view should be the same as the leave slip view.
      
**Life Studies**
- [ ] The reports generated and printable for Life-study assignments is incorrect need to meet with Andrew for requirements _Are these correct now? 9/8_
- [x] When a TA is assigning a life study manually they should be able to select multiple trainee's similar to selecting many on group leave slip.  #1443 
- [x] On the Assign life-study to single trainee page, you can also select TAs. But only trainees should be on that dropdown list. _from JRumb_ #1443 
- [x] Is there a way to indicate (or archive) completed assignments? There is no way to tell if submitted summaries are completed and approved.
      
**Room Reservations**
- [x] There are two date fields on the page that creates room reservations. Per discussion from meeting we should hide the entire date that is on the top of the table. @kcmin
- [ ] Need a way to print schedules. Right now many things are cut off.
- [ ] When inputting times, you can either use the drop-down menu or type it in. However, if you don't type in a type on the half-hours (e.g., :00, :30), approving the room reservation request is not reflected on the schedule. For example, I approved a request for 6:15-6:35, and nothing showed on the schedule. It would be better to remove the option to type the time in since the schedule is based on every 30 minutes. @kcmin
- [ ] Freeze the "Time Slots" column on http://10.0.8.35/room_reservations/schedule so that it continues to show when scrolling horizontally.
- [ ] Have a way to list two pending room reservations that coincide with each other. 
- [ ]  Updating a room reservation I originally submitted to extend the time shows the following error: "Re-check the date of the start and end times. There is an overlap with an already approved room reservation." Looking at the schedule, there is no conflict, besides the reservation itself that is being updated. @kcmin 

**Web Access Requests**
- [x] No way to unmark a request once you have selected marked for fellowship. Needs to be
a way to unmark for fellowship to be consistent with site (also noticed on other modules,
such as Web Access) @finben 

**Semi Annual**
- [x] Merge semi-annual study location and semi-annual study attendance pages. Include functionality to for TA to approve or deny alternate study location requests, and to change study location assignment. #1411 
- [x] Make semi-annual study attendance report more compact; you currently have to scroll horizontally. Change "Attended (A)" to "Present (P)", and "Unexcused (U)" to "Other Absence (A)". Remove Fellowship (F) and illness (I) options. Have attendance default to blank or absent. #1483 
      
**Other**
- [ ] Trainee's added to designated services are not automatically given links to input designated service hours #1442 
- [ ] Add a way to take attendance and assign discipline for missed services, rotational, or designated #1131 @samvictor232
- [x] Date formatting on TA leave slip list view should match the format on the requests tables. Update: For all requests: Have "May 05" format on summary lists and "MM/DD/YY 00:00 AM" format on detail views
- [ ] Sorting by date on request pages (audio, framing, linens, maintenance, room reservation, and web access): The summary table at the bottom of the page has dates in the right order, but it starts at 10/18/2018 and then in the middle of the list, it jumps back to 08/15/2018 which is the start of the term. Announcement requests are mostly ordered, but there's a request set for 10/20 at the top that breaks the order. 
- [ ] Add a force page for designated service  - Angelo
- [ ] Build a Gospel Statistics Module  - Zion
- [ ] Build a House Inspectors Module
- [x] The scrolling announcements get cut off when the TV page refreshes. An issue when we have longer announcements.

**Comment by finben** [comment]
Issues have migrated to #1560
