### ISSUE TITLE
TA Issues - 12/1/2018

### ISSUE THREAD

**Issue by JoannaRumbley** [attendanceproject/djattendance#1525]
**Attendance Rolls**
- [ ] Add force page when submitting attendance late. 
- [ ] Button to change attendance period is still only one-pixel large on Firefox. It isn't intuitive either.

**Class Notes**

**Extra Fields**
- [x] Does not affect perfect attendance will be a built-in leave slip category” (Automatic for Conferences, team trips, house meals, service, fellowship, and allow for TA override**) @joysyu 

**Gospel Trips**
- [ ]  Trainees report getting a blank page after trying to submit (specifically we believe this is tied to Chrome browser)
- [ ] When generating a report, if I generate a report containing "Allergies" plus any other field, the ability to search and generated CSVs, etc. disappears.
- [ ] Add functionality for us to add finance coordinators, media coordinators, and report/statistics coordinators. It would be in the same principle as the trainee contacts.
- [ ] I have just inputted the trainee contacts for the gospel trips. When looking at the report on the webpage, a check mark shows. However, when downloading the CSV, nothing shows. Can there be a simple “Yes” indicator? Along these lines, “team contact” should be renamed “trainee contact”.

**Leave Slips** 
- [x] Automatically approve when the TA submits as leaveslip. @davidhtien #1534 
- [x] Have leave slips show the date and time they were submitted.
- [ ] **Critical** Issue of multiple leave slips for the same roll call cancelling one another. For example, I approve a leave slip for a roll call, but the attendance does not reflect the approval because there is another leave slip for the same roll call that was not processed or denied. 
- [ ] When a leave slip is marked for fellowship have a note of who marked the leave slip for fellowship, so the trainee knows who to go to. (We need to visit this along with the bigger idea of a messaging module)
- [ ] There are still issues with how the attendance server processes leave slips for the same roll call(s). Example: Celine Goh submitted four leave slips for Lord's Day curfew and/or lights out for 9/23. One was approved. However, when you pull up any of the other three leave slips, the roll call still shows the absences.
- [ ] When pulling up a leave slip, the calendar only shows the absences and tardies for that leave slip. We would like to see the trainees' complete attendance. In other words, when viewing the weekly calendar, the trainee attendance view should be the same as the leave slip view.
- [ ] Add "Does not count against perfect attendance" check box and functionality.

      
**Life Studies**
- [x] The reports generated and printable for Life-study assignments is incorrect need to meet with Andrew for requirements _Are these correct now? 12/1 @JoannaRumbley _
      
**Room Reservations**
- [ ] Need a way to print schedules. Right now many things are cut off.
- [ ] When inputting times, you can either use the drop-down menu or type it in. However, if you don't type in a type on the half-hours (e.g., :00, :30), approving the room reservation request is not reflected on the schedule. For example, I approved a request for 6:15-6:35, and nothing showed on the schedule. It would be better to remove the option to type the time in since the schedule is based on every 30 minutes.
- [ ] Freeze the "Time Slots" column on http://10.0.8.35/room_reservations/schedule so that it continues to show when scrolling horizontally.
- [x] Have a way to list two pending room reservations that coincide with each other. @kcmin ( We didn't implement it this way. We just made it so that a trainee cannot submit a room reservation if there is a coinciding one pending already. We ask the trainee to either change room or time.)
- [x]  Updating a room reservation I originally submitted to extend the time shows the following error: "Re-check the date of the start and end times. There is an overlap with an already approved room reservation." Looking at the schedule, there is no conflict, besides the reservation itself that is being updated. @kcmin 

      
**Other**
- [ ] Trainee's added to designated services are not automatically given links to input designated service hours #1442 
- [ ] Add a way to take attendance and assign discipline for missed services, rotational, or designated #1131 @samvictor232
- [ ] Sorting by date on request pages (audio, framing, linens, maintenance, room reservation, and web access): The summary table at the bottom of the page has dates in the right order, but it starts at 10/18/2018 and then in the middle of the list, it jumps back to 08/15/2018 which is the start of the term. Announcement requests are mostly ordered, but there's a request set for 10/20 at the top that breaks the order. 
- [ ] Add a force page for designated service  - @AngeloBelUCSD 
- [ ] Build a Gospel Statistics Module  - @zioninzion 
- [ ] Build a House Inspectors Module
- [ ] Create a new survey module, similar in format to the exam module.
- [ ] Clean up announcement request page - summarize announcement list into a table and create detail pages, like how the maintenance request page is formatted. @Sam-Lam

**Comment by finben** [comment]
List has been updated. Issues have migrated to #1560
