### ISSUE TITLE
TA Issues - 12/20/2018

### ISSUE THREAD

**Issue by finben** [attendanceproject/djattendance#1560]
Updated List,  As usual please note if you are working on an issue so we don't have multiple people working the same bugs. Also, please do not mark as complete until the issue has been merged into dev. Jesus is Lord! 

**Accounts**
- [ ] Remove all Boston-XB trainee's from the server --> Copied to #1597 
- [x] The "General Saturday TA brothers" account should be able to access admin tabs to open and close exams or use leave slip module.
They should have similar or same permissions as the TA's
- [x] Whenever I try to change identity, the following error page shows: "Forbidden (403) CSRF verification failed. Request aborted. More information is available with DEBUG=True." If I refresh the page, it does not take me to the trainee account, but to the change identity page.
      
**Attendance Rolls**
- [ ] Add force page when submitting attendance late. --> Moved to future projects
- [ ] Unable to make changes to team or house attendance, plus any other pages that are formatted like those two pages. We would have to make changes to each trainee's personal attendance.

**Gospel Trips**
All Gospel Trip bugs are on a separate issue #1548 

**Graduation**
- [ ]  Need functionality to be able to edit the questions and for a TA to see what the trainee sees.

**Leave Slips** 
- [ ] Issue of multiple leave slips for the same roll call cancelling one another. For example, I approve a leave slip for a roll call, but the attendance does not reflect the approval because there is another leave slip for the same roll call that was not processed or denied. 
- [ ] There are still issues with how the attendance server processes leave slips for the same roll call(s). Example: Celine Goh submitted four leave slips for Lord's Day curfew and/or lights out for 9/23. One was approved. However, when you pull up any of the other three leave slips, the roll call still shows the absences.
- [ ] When pulling up a leave slip, the calendar only shows the absences and tardies for that leave slip. We would like to see the trainees' complete attendance. In other words, when viewing the weekly calendar, the trainee attendance view should be the same as the leave slip view.
- [x] Add "Does not count against perfect attendance" check box and functionality.
- [x] Show date and time the leave slip was originally submitted 
- [ ] Discrepancy between personal attendance records and viewing attendance via group leave slip caused by group leave slip view trying to show personal attendance of multiple trainees. Fix by only showing generic group schedule when pulling up any group leave slip from any view, TA or trainee. Talked to Carlos about this.
- [ ]  When switching to an account of a trainee with pending leave slips, I noticed that the number of the homepage reads zero for
pending leave slips. Example: Ivie McMillan.
- [ ] Need functionality to transfer discipline already assigned from one trainee to another.

**Reports**
- [ ] Generate grade and attendance reports by gospel team and sending locality. --> Eventually move this to the server instead of having AP manually put it together and send it
- [ ] Make semi-annual study attendance report more compact; you currently have to scroll horizontally. Change "Attended (A)" to "Present (P)", and "Unexcused (U)" to "Other Absence (A)". Remove Fellowship (F) and illness (I) options. Have attendance default to blank or absent.

**Room Reservations**
- [ ] Need a way to print schedules. Right now many things are cut off.
- [x] When inputting times, you can either use the drop-down menu or type it in. However, if you don't type in a type on the half-hours (e.g., :00, :30), approving the room reservation request is not reflected on the schedule. For example, I approved a request for 6:15-6:35, and nothing showed on the schedule. It would be better to remove the option to type the time in since the schedule is based on every 30 minutes. --> @kcmin working and seemingly bug-free in #1628. the javascript could be improved, but i am not that experienced and time is limited.
- [x] Freeze the "Time Slots" column on http://10.0.8.35/room_reservations/schedule so that it continues to show when scrolling horizontally. --> fixed in #1605 

**Semi-Annual**
- [ ] Merge semi-annual study location and semi-annual study attendance pages. Include functionality to for TA to approve or deny alternate study location requests, and to change study location assignment.

**Design Implementations**
- [ ] It is not clear when a marked for fellowship toggle is marked or not. The design should be more obvious when it is marked for
fellowship versus not on all modules
- [ ] Buttons should be "greyed-out" and unclickable if already approved, finalized, etc. for all modules
- [ ] Standarize summary table designs across modules (e.g., maintenance requests, leave slips, web requests, room reservations, announcements, etc.). I talked to the designers about this.
- [ ] Get rid of all blue ajax pop-ups that say "saved" "submitted" that appear when TA's work on leave slip processing 

**Other**
- [ ] Sorting by date on request pages (audio, framing, linens, maintenance, room reservation, and web access): The summary table at the bottom of the page has dates in the right order, but it starts at 10/18/2018 and then in the middle of the list, it jumps back to 08/15/2018 which is the start of the term. Announcement requests are mostly ordered, but there's a request set for 10/20 at the top that breaks the order. 
- [x] Add a force page for designated service - Angelo
- [x] Build a Gospel Statistics Module - Zion
- [ ] Build a House Inspectors Module - Angelo
- [ ] Clean up announcement request page - summarize announcement list into a table and create detail pages, like how the maintenance request page is formatted. @Sam-Lam

**Comment by JoannaRumbley** [comment]
Remaining issues (not including the one for future projects) have been moved to #1597
