### ISSUE TITLE
ROADMAP: Major Items left to do for P2 Release

### ISSUE THREAD

**Issue by radicalray** [attendanceproject/djattendance#230]
- [ ] Home Profile page (Miriam is currently designing
  - [x] Messages, reminders weekly run (celery)
- [ ] TA View (attendance, web-access request, leaveslip approval, life study approval etc...)
- [ ] Taking Roll (attendance monitor, TA, 2nd year trainee)
- [x] Group Leaveslips
- [ ] Permissions (urls-menus, views, rest API, wiki?)
- [ ] Reporting (attendance, absentee roster, bible tracker)
- [x] Service Scheduling

---

Fixes:
- [ ] Finish Exams
- [x] Fix Badges bugs
- [ ] redo UI for life studies

@lifedispenser @davidhtien @elizajyl @ichootheword @rayoowoo @rochellewang 

Is this correct, what's left? Am I missing anything major?

---

Dev Ops TODO Items:
- [x] Internal wiki like github for knowledge transfer and server maintenance in the future
- [x] backup db and commit to git under revision control, sync with dropbox (TA with dropbox privilege at all times for continuity)
- [x] celery workers for messages/life study assignment working

**Comment by radicalray** [comment]
- [ ] Permissions -> template/group fixin
 - [ ] Rest Framework Permission
 - [ ] HTTPS (@snowboarder003)
 - [ ] Notification System (messages)
 - [ ] Schedules CRUD @schai6 
 - [ ] Trainee list picker
 - [ ] Import @haileyl 
 - [ ] RFID Rolls @jontey @snowboarder003 @radicalray
 - [ ] Web sockets
 - [ ] verse_parse @snowboarder003 #181
 - [ ] TA Leaveslip Approval @schai6 

Devops:
 - [ ] feedback, feature request page
 - [ ] Migrations slowing down, do we need to squash? @radicalray
 - [ ] AV Server
 - [ ] Test Server @swenghj 
 - [ ] Gitlab @snowboarder003 @radicalray
 - [ ] Travis CI @swenghj 
 - [ ] Slackbot deploy @swenghj 

PM

 - [ ] Enter in schedule data @rochellewang 
 - [ ] Humanize URL + Page titles/menu items, instructions, default messages
      - [ ] Keep url/naming convention consistent
