### ISSUE TITLE
Bible Reading Tracker bugs

### ISSUE THREAD

**Issue by rayoowoo** [attendanceproject/djattendance#334]
#### Daily Reading Page
- [x] selecting complete daily reading - future weeks' information should be not changeable. just the current week.
- [x] selecting complete daily reading - no finalize button  **Can you ask the TA's? I think Danny said last term we dont need it anymore**
- [x] selecting complete daily reading - ^relies on this, but past weeks' information should also not be changeable. just current week + previous week up until Tuesday
- [x] When refreshing the page on a tab, url should be updated to: #firstyear or something so the tab remains open across refreshes
## Bible Reading Reports
- [x] list of trainees on the report - the list of "trainees" is actually the list of all the users, not the list of trainees.
- [x] filter for table - if a checkbox selection is at the top of the page, why is there a need for an additional "show/hide columns" option for the table?
- [x] generating a report - before displaying the correct report with the selected filters, a table with all the trainees and all the information fields will appear very briefly
- [x] generate CSV report - it works, automatically downloaded. except that the title "Firstname" has weird symbols (Ã¯Â»Â¿"Firstname")
- [x] generating a large PDF report - if the PDF is large, the page is initially "about:blank" and looks like it didn't work. it takes a while for the page to look differently
- [x] generating a PDF report - There is no legend for the titles on the table (C%, N#, etc.). maybe we should have one.
- [x] generating a PDF report - Because the percentages are rounded off to whole numbers, some of the percentages do not add up to 100%. should we make this clear that this is the case?
- [x] selecting dates - is there a need for selecting a monday and then a Lord's day? can't we just select by week #'s? **Can you ask the TA's?**
- [x] Bible Tracker progress bar seem to be broken on production server #276
- [x] Bible reading data is from earlier in the term, and does not reflect the data at the end of the term.

**Comment by radicalray** [comment]
Also, don't forget to test bible reports under: bible_tracker/reports I think. 

Ray

**Comment by rayoowoo** [comment]
|Functionality / Cases	|Comments	|Label	|Resolution	|Priority|
|-----------------------|---------------|-------|---------------|--------|
|list of trainees on the report	|the list of "trainees" is actually the list of all the users, not the list of trainees.| 	BUG||		4|
|filter for table	|if a checkbox selection is at the top of the page, why is there a need for an additional "show/hide columns" option for the table?|	NOT SURE||		5|
|Show trainees who have completed LESS THAN ____% of their completed and maedup (C+M%) readings	|it works.||||			
|date changes	|it works.|		|	||
|selecting filters for the table	|selecting the filters on prior to generating the report will include those fields on the table.||	||		
|generating a report	|before displaying the correct report with the selected filters, a table with all the trainees and all the information fields will appear very briefly|	BUG|	|	3|
|generate PDF report	|it works. the pdf is opened in another tab|	|	||	
|generate CSV report	|it works, automatically downloaded. except that the title "Firstname" has weird symbols (Ã¯Â»Â¿"Firstname")|	SMALL|		|5|
|generating a large PDF report	|if the PDF is large, the page is initially "about:blank" and looks like it didn't work. it takes a while for the page to look differently|	SMALL|		|5|
|search trainees	|it works; for both first and last names||	||		
|scrolling down the page keeps the table titles at the top of the window	|works!| |	||		
|sorting the table via the various filters|	works! 	|||	|	
|generating a PDF report	|There is no legend for the titles on the table (C%, N#, etc.). maybe we should have one.|	MISS|		|5|
|generating a PDF report	|Because the percentages are rounded off to whole numbers, some of the percentages do not add up to 100%. should we make this clear that this is the case?|	NOT SURE|		|5|
|selecting dates	|is there a need for selecting a monday and then a Lord's day? can't we just select by week #'s?|	NOT SURE|		|5|

**Comment by radicalray** [comment]
When refreshing the page on a tab, url should be updated to: ```#firstyear``` or something so the tab remains open across refreshes

**Comment by billyeh** [comment]
done in #437!
