### ISSUE TITLE
List of past issues

### ISSUE THREAD

**Issue by rayoowoo** [attendanceproject/djattendance#347]
So I combed through some of the past issues (so not exhaustive), and compiled a list. On this list will be short descriptions, but for the full conversation just go to the issue itself. If an issue needs to be reopened, please reopen them. I'm just trying to clean up the issues. Otherwise, if not, we can just clear these things with the checkboxes.

### Questions & Ideas

- [ ] #27 Displaying weekly reading assignments on homepage (depends on syllabus)
- [x] #79 denying Lord's day evening night out leave slips if the trainee has Monday discipline
- [ ] #34 form builder - for one-time or regular questionnaires
- [ ] #9 Visa support - should we add functionality for visa support?
- [x] #29 Digitizing the books
- [x] #12 external deployment
- [ ] #31 potential notifications module
- [ ] #19 Locality information - what kind of information needs to be associated with locality?
- [x] #69 Pushing documents to trainees over the server instead of printing paper copies of handouts every time
- [x] #22 handle event and error logging for analytics and debugging purposes
- [x] #64 what categories should be available for user-submitted bug reports? and how should this affect the way we structure our github issue labels?
- [x] #155 Book collection should include order?

### Suggestions
- [ ] #152 Get rid of Deprecation Warnings and speed up code reload
- [ ] #156 Figure out how to sanitize forms via rest_framework ajax requests
- [ ] #167 Squash migration files to speed up initial install and future makemigrations
- [x] #170 Manage_celery.sh stop buggy
- [ ] #25 load testing - we should do load testing for certain modules, especially exams, which will be used by many users at once. 
- [ ] #40 Figure out if we can use Google analytics or something similar to collect user information/statistics
- [x] #154 Django admin many-to-many select2 fields buggy

### Tasks
- [x] #5 Check with the kitchen to see if it would be helpful for the server to accumulate meal attendance for them.
- [x] #13 Find out whether official time is still going to be the clock or the server
- [x] #24 scheduled backups
- [x] #51 Do sister trainees need a 2nd TA field?
- [ ] #87 clean up static assets
- [ ] #171 Find better place to put js/django-jquery-init.js
- [ ] #200 Grades
- [ ] #245 Make good pages titles for all the pages
