### ISSUE TITLE
Attendance Remaining Functionality

### ISSUE THREAD

**Issue by czhaocmu** [attendanceproject/djattendance#457]
### 1. Personal Attendance main (Role: Trainee)

**Functionality**

**UI**
- [x] Remove legend button (show the legend by default)
- [ ] Leaveslips under Personal Attendance should have a legend as well, showing what the different states mean
- [x] Remove pixel from between events that show up adjacent on the schedule calendar
- [x] Should the week that the calendar is displaying be dark blue background with blue bar underneath, indicating non-clickable tab? (see attached picture)

![trainee attendance_summary](https://user-images.githubusercontent.com/23424787/29999339-5aa97d0c-8ff9-11e7-8f61-4806ed4a1611.png)

- [x] Add legend to know what the color of events mean
- [x] Add Note: Report information will not be up-to-date until attendance office hours (i.e., when the potential violators list is posted). #471 d610c55a41d71744a8f9872d372511fdfa2c9ec8
- [x] Add title to Attendance page as seen on browser tab (FTTA|Personal Attendance) #471 d610c55a41d71744a8f9872d372511fdfa2c9ec8

Nice to have*
- [ ] Add lines to separate days and times
- [x] Add dropdown to select attendance period 136946f4f83ec43141992edf9c0e618d24575ccc
- [x] Add month of date in calendar header

**Permissions**
- [x] ~~First year trainees~~Non self-attendance trainees should not have roll button #471 48e46ab1ee391fbe2066b52a79872dd64468a0a6
	
### 2. Personal Attendance->Roll (Role: Second Year Trainee)

**Functionality**
- [x] Finalize attendance starting Mon to end of Tues #471 86136070a72eabe66988ac50afc19a76b0206a7f

**UI**
- [x] Add notifications that roll was not finalized. #471 de7f71d937ef6d35fde34343bf9c5a91d9e31dd7

**UX**
- [x] Remove all sessions closes the entire Roll or Leaveslips box?

**Error Handling**
- [x] When no sessions are selected, submit button is not disabled. 
- [x] Should not be able to submit attendance for future and past weeks. #471 969b1d68ec0ae3a69582491f4acc42f9468fd395

**Permissions**
- [x] Add 

### 3. Personal Attendance->Leaveslips (Role: Trainee)

**Functionality**
- [x] Add last slip date for meal out and night out with contact info form. #471 dcba24b81544a1de7f483fb57fee0e0114258766
- [ ] Add submitted late to leaveslips after 48 hours.

**UI**
- [x] Add Meal sign out: If your leave of absence permits you to miss a meal, you must also sign out on the appropriate meal sign-out sheet.
Service scheduling: If your leave of absence permits you to be out of the schedule for seven days or more, you must also submit a note to the service scheduling mail slot. #471 5d4903fa38590188e9d42dcfa5e1a4602e22a238
**UX**
- [x] For radio buttons under "More" for leaveslip reason, you have to click the radio button and cannot click just the text #471 c15e89e4798ef382a4545e28bd69054d09db2f6a

**Error Handling**
- [x] When no sessions are selected, submit button is not disabled. 

### 4. View and Edit Roll by Trainee (Role: AM and TA)
- [x] Add #471 dbbaacb66835f3d339c2af512e1fef66627e652b

### 5. Approve and View Leaveslips by Trainee (Role: TA)
- [x] Add #477

### 6. Submit Designated Service Attendance
- [ ] Missing

### 7. Submit Team, House, YPC Attendance (Role: AM, TM, HC)
**Functionality**
- [x] Attendance Monitor needs to be able to select any team/house to modify attendance (might need to unfinalize)
- [ ] Attendance Monitor needs to finalize attendance for team/house
- [ ] Doesn't list the house name
- [ ] No save and finalize button
- [ ] Seat Map not working
- [ ] Notifications that attendance was not finalized

**UI**
- [x] Do we need colors like to indicate approved absences (green)?

**UX**
- [ ] Do we need the pagination?

**Permissions**
- [x] Non HC's should not be able to see House attendance
- [x] Non Team monitors should not be able to see Team Attendance
- [x] Attendance Monitor should be able to see all attendance

**Error Handling**
- [ ] Should not be able to submit attendance for future and past weeks. 

### 8. Submit Class, Study, and Meal Rolls (Role: AM)

**Functionality**
- [x] Submit attendance by table form when no seating chart is available
- [x] Go to previous weeks to submit roll

**Permissions**
- [x] Non-AM should not be able to see these rolls

### 10. Audit? (Role: AM)

**Comment by czhaocmu** [comment]
### Personal Attendance main (Role: Second Year Trainee)

**Functionality**

**UI**
- [ ] Add legend to know what the color of events mean
- [ ] Add Note: Report information will not be up-to-date until attendance office hours (i.e., when the potential violators list is posted).
- [ ] Add lines to separate days and times
- [ ] Add dropdown to select attendance period
- [ ] Add month of date in calendar header
- [ ] Add title to Attendance page as seen on browser tab (FTTA|Personal Attendance)

**UX**

**Error Handling**
- [ ] When no sessions are selected, submit button is not disabled.
