### ISSUE TITLE
Leaveslips TA Views - TODO

### ISSUE THREAD

**Issue by jontey** [attendanceproject/djattendance#476]
Some thoughts to improve leaveslips display for TAs

- [x] Change color for calendar display to be more obvious which events are selected #518
- [x] Old Server shows trainee's house and team
- [x] If type is house night out or meal out, show last approved night out for trainee #518
- [x] Add TA private remarks.. (for between TAs) #518
- [x] Individual Leaveslips should show trainee's attendance report #518
