### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by swenghj** [attendanceproject/djattendance#479]
* Test tasks
- [ ] Absentee Trainee Report
  - [ ] execute test plans 
  - [ ] automation 
- [ ] House Attendance 
  - [ ] execute test plans 
  - [ ] automation 
- [ ] Life Study 
  - [ ] execute test plans 
  - [ ] automation 
- [ ] Bible-Reading Tracker 
  - [ ] execute test plans 
  - [ ] automation 
- [ ] Seat Charting 
  - [ ] execute test plans 
  - [ ] automation 
- [ ] Web Access Requests 
  - [ ] execute test plans 
  - [ ] automation 
- [ ] Badges
  - [ ] execute test plans 
  - [ ] automation 
- [ ] Leaveslips
  - [ ] execute test plans 
  - [ ] automation 
- [ ] Schedules
  - [ ] execute test plans 
  - [ ] automation 
- [ ] Rolls
  - [ ] execute test plans 
  - [ ] automation 
- [ ] Exams
  - [ ] execute test plans 
  - [ ] automation

**Comment by billyeh** [comment]
Useful page on testing django: https://dezoito.github.io/2015/09/21/how-to-test-django-applications_pt1.html
