### ISSUE TITLE
TestCase: House Form Requests

### ISSUE THREAD

**Issue by swenghj** [attendanceproject/djattendance#492]
### Maintenance 
- [ ] maintenance requests 
 : check if you can create a request 
  - [ ] check your current residence is displayed
  - [ ] check if you current residence can be changed 
  - [ ] check if you can set up; type, room, priority 
  - [ ] check if you can describe a problem in details 
  - [ ] check if you see submit 
- [ ] maintenance report
 : check whatever has been submitted, it should appear in the report when you open 
### Linens 
- [ ] linens requests
 : check if you can create a request 
  - [ ] check your current residence is displayed
  - [ ] check if you current residence can be changed 
  - [ ] check if you can set up; item, quantity, reason 
  - [ ] check if you see submit 
- [ ] linens report
 : check whatever has been submitted, it should appear in the report when you open 
### Framing 
- [ ] framing requests
 : check if you can create a request 
  - [ ] check your current residence is displayed
  - [ ] check if you current residence can be changed 
  - [ ] check if you can set up; location, fix or replace, broken explanation, frame quote
  - [ ] check if you see submit 
- [ ] framing report
 : check whatever has been submitted, it should appear in the report when you open 
### Furniture 
- [ ] check if possible to view a report
 : does not have submission link, but has a report

**Comment by swenghj** [comment]
## Issues 
- [ ] fix all the three reports links(maintenance, linens, framing) 
- [ ] Furniture report link is not showing 
- [ ] Missing fields 
  - [ ] Maintenance - house

**Comment by ksungreborn** [comment]
Under 'Requests' tab this is listed as 'Maintenance Requests', it should probably be 'House Requests' to cover the various requests under house requests.
