### ISSUE TITLE
Feedback Updated 03-17-18

### ISSUE THREAD

**Issue by finben** [attendanceproject/djattendance#874]
Priority Key
HP = High Priority
MP = Medium Priority

**Leave slips:**
- [x] TA informed should be a field that doesn’t affect where the leave slip goes 0768dae38a1cadac66e1d0fd464c8da2aa65b27e

- [ ] **HP** TA's are unable to change the events on a pending leave slip this should be editable for them @joeyu23 

- Assigned TA 
  - [x] should be trainee’s default TA or transferred TA (Trainees don’t see this) @billyeh 5601e08
  - [x] Leave slip count is wrong on TA landing page 1bb420f52ee0c27480ad6ac2e521199da1a6741f
  - [ ] Filter out Saturday TAs

- TA sisters
  - [ ] Transfer and approve button (automatically transfers to linked TA brother)
  - [ ] Save button (allows TA sister to make edits to leave slips, including TA informed)
  - [ ] Transfer button (allows TA sisters to transfer to linked TA brother without approving it)

- [x] Allow all leave slip fields to be edited by TA @iamsitting 0768dae38a1cadac66e1d0fd464c8da2aa65b27e

- [ ] **HP** Change list view so that we can approve multiple leave slips without the lag of the screen being refreshed.

- [ ] **HP** Leave slips default to "Yes, TA informed" with the name of a TA. This results in many inaccurate leave slips. The default should be blank and the trainee should be required to make an input.

- [x] **HP** Unable to view processed leave slips.

- [ ] **MP** TAs unable to see all the different fields on a night out leave slip on detailed page. Would need to change identiy to the trainee. @bdou 

- [ ] **HP** Trainees unable to see TA comments on leave slips. 

- [ ] **MP** Unable to transfer group leave slips.

- [ ] Meal cleanup leave slips also excusing trainees from the meals themselves. Not an issue with the start time of the leave slip.

- [ ] Multiple tabs popping up when opening detailed pages for leave slips. Should go straight into the page in the same tab

- [ ] The leave slip submission acknowledgement disappears too quickly

- [ ] Allow trainees to access previous Leave slips. Maybe a ListView for trainees.

**Extra field:**
  - [ ] “Does not affect perfect attendance” (Automatic for Conferences, team trips, house meals, service, fellowship, and allow for TA override)

- [ ] Add functionality to "sign out" of Monday dinner via leave slip.

- [x] Hover over event for start time, event name, and reason 5119ce9

- [x] Color code Leave Slips status codes on personal attendance @bdou 

**ROLLS:**
- [ ] Add force page when submitting attendance late.

- [ ] House and Team Roll (make a dummy save, and finalize button) @priscilagonzalez 

- [ ] Implement way for 2nd years on first attendance

- [ ] Need unfinalize roll button

**BIBLE READING TRACKER**
- [ ] We no longer need a notification saying trainee has not finalized Bible reading since this is an impossibility with the force page @yipingbenjaminliu 

**Web Access Requests:**
- [ ] For TAs: order by status (Pending, Fellowship, Approved, Denied) then by submission date @iamsitting #870 

- [ ] Urgent text should be red @bdou 

- [x] **MP** Bug: Mark for fellowship actually approves @iamsitting (works for me)

**ROOM RESERVATIONS:**

- [ ] Rooms are not in alphabetical order after editing available rooms

- [ ] Schedule needs to be imported into the new attendance server

- [ ] Room choices are not in alphabetical order after editing available rooms.

**TA Landing Page**
- [ ] TA's should see their personal number of items as well as a total number of items. Ex. web access requests 5 (390). The only exception is leave slips which should only show the TA's personal number of slips

- [x] Remove housing from TA landing page as they do not need this 0815c9b

**TA List Views**
- [ ] Get rid of comment button from TA announcement list view for consistency across site. 

- [ ] All TA list views need the following sort order (Pending, Marked for Fellowship, Approve, Deny) to stop them from having to excessively scroll. Secondary sort needs to be time submitted based

- [ ] For Leave Slip TA list view Add attendance period column on list view.

- [ ] "View leave slips for" on list view includes people who are not TAs.

- [ ] Trainee names need to be made more visible (increase font size)

- [ ] Across site lists need delete options for items from TA list view

- [ ] "Texted attendance number" notation on list view should be capitalized for consistency.

**ABSENTEE TRAINEE ROSTER**
- [x] Change "Everyone is Present!" text to "All Present" @yipingbenjaminliu dcca3503210217bf453a257d603efaf5c2fdc274

**REPORTS**

- [ ] The reports generated and printable for Life-study assignments is incorrect. Andrew Li is requesting for someone to meet with him to go over the Life-studies module. @finben will meet with Andrew then work with @yipingbenjaminliu

**Other:**
- [ ] **HP** FTTA-XB application is need @ryanli633 

- [ ] **MP** HC Survey TA's are looking for a way to edit what the survey asks, edit times, and delete the server

- [ ] **MP** Trainees with designated services need to input their service hours. #868 

- [ ] **MP**Button to change attendance period is only one-pixel large on Firefox. Also not intuitive.

- [ ] Add dishware requests to linens since they are taken care of by the same service team

- [ ] House Requests, Room Reservations, Life Studies, Class notes, are user (Trainee or TA) specific.

- [ ] Trainees with designated services need to be able to input their service hours (ex Greg Lee Transportation) #868 

- [x] Graduation module needing DVD numbers, grad invites, and remembrance pages @yipingbenjaminliu 58bb827

- [ ] Have a way to take attendance and assign discipline for missed services, rotational or designated.

- [ ] Too many trainees can submit linens requests.

-----------------------------------
COMPLETED

Announcements: eb42242506ed2c1933c171d1184fa4014efe3820
-  [x] Auto-approve announce request for TAs (Hide status field for TAs)

- [x] Bug: Submitted by “None” when it’s submitted by a TA

- [x] In TA list view the submitted by includes trainee email inconsistent with other list views. Email not needed

- [x] fix switch identity page trainee selector

-Leave Slips
- [x] Better feedback for Leave Slip submission. (@davidhtien) 2e43ec1 
@billyeh , maybe make something similar to what bible_tracker does right now, flash a save. take a look at https://github.com/attendanceproject/djattendance/blob/eaa38a736f934c3a2e9e23db18c3176f8bc65ab6/ap/bible_tracker/templates/bible_tracker/index.html#L480-L482
https://github.com/attendanceproject/djattendance/blob/eaa38a736f934c3a2e9e23db18c3176f8bc65ab6/ap/bible_tracker/templates/bible_tracker/index.html#L271-L272

- [x] After approving leave slip, redirect to next pending leave slip 8b1ec8ceca41635aae918984ed5cdc62bf23b798

-Extra Field

- [x] Need more obvious event highlighting when editing/reviewing leave slips 94b37d7f0e319cd962c02ca21248fa59a54c94a8

- [x] Show submission date on leave slip detail @samvictor232 76354fa900280d7268a56cdb02a5b55fe60ad1bc

- [x] Add “last slip” to meal/night out, even if there isn’t one on record 652eb48bc

- [x] On ListView, Month abbreviations are not consistent @samvictor232 50d2da0c62eea24157c3a2b4661322f572a72864

- [x] Group slip approve/fellowship/deny buttons need to be bigger @samvictor232

- [x] Trainees should be able to edit their own leave slips as long as the leave slip is still in pending status

-Rolls

- [x] Team Roll is not auto-saving

- [x] 2nd year rolls finalize button has vague feedback

- [x] TA needs permission to submit rolls 7a31214191df594c151d1a89182b574fe8f558ea

Trainee items:
- [x] Allow trainees to see linens requests for trainees. fbc394c

Life-studies:
- [x] Search function for Life Study ListView 7a8dd6d9cf5475a5ce2cc13d6ff5167300cc63d0

- [x] Populate with life-study books

- [x] Decrease Life Study Penalty ce0a11e

- [ ] When trying to mark a Life-study summary that is manually entered, nothing happens.

Web Access Requests:
- [x] Urgent value is not shown for nonurgent request detail views @bdou 

- [ ] Seeing web access requests submitted by "none" (e.g., http://10.0.8.35/web_access/detail/384).

Other:
- [x] Maintenance request brothers want a csv export to fit their current workflow af830b88b54425eb076f51eeaf04b2ae442e3592

Room Reservations:
- [x] Requests do not match landing page count c83dad736cb418fae0d8161eee6eb2d1a867ad62

- [ ] When editing a room reservation request, the title page is "FTTA | Room Reservation", but on other pages it is pluralized.

Absentee Trainee Roster:
- [x] Absent Trainee Roster is not needed on Monday (related: # days on report should not reset after Monday) 4601138180c00912a5c41378b850fac9762f1659

- [x] Change Email account name to something better than “AP Server” d650605f2

- [x] Remove "Coming to Class" as an option 71be9bb48d346f84f24e102a2839a3493d330154

Attendance:
- [x] Allow TAs to change self-attendance field for 2nd year trainees 0da336236ef01c9087cb4140395d84f9e8bc4fab

**Comment by finben** [comment]
Please use updated list #898
