### ISSUE TITLE
Feedback Updated 03-24-18

### ISSUE THREAD

**Issue by finben** [attendanceproject/djattendance#898]
**Critical Issues:** 
(These are Highest Priority issues (On the TA spreadsheet, they're colored magenta)

- [ ] There does not see to be a way to assign discipline based on attendance

- [ ] Trainees unable to see TA comments on leave slips. / Update: Issues with TA comments. Inputting comments and clicking on deny does not save the TA comments. You need to input TA comments, then SAVE before clicking deny. Only then will the trainee be able to see the TA comments.

- [ ] Not a bug per se, but until the issues with the Life-study module are addressed, Andrew would like a print-out of the Life-study summaries that were supposed to be assigned from the last attendance period.

- [ ] TAs unable to edit leave slips (Still not working for group slips)

- [x] Fix TA sisters' transfer process. TA sisters' transfer process should not approve leave slips by default. @davidhtien: we can't reproduce this behavior, need more details or an example

- [ ] Program TA brother/TA sister pairs for TA sister leave slip transfer process. Use the pairings from the old attendance server.

- [ ] Approved leave slips are not being reflected on attendance. Example: See Andrew Jen's attendance and leave slips (2257, 2258, 2259) for 3/11. May be due to other leave slips being previously denied for that same roll call.

- [ ] Ensure graduation module is complete. Should have FTTA-XB Application, Graduation DVD, Graduation Invitations, Fourth Term Considerations, Graduation Program Remembrances, Testimony, and Graduation Program Outline Burden, with respective report pages for each. Missing at least four sub-pages.

- [ ] The reports generated and printable for Life-study assignments is incorrect. Andrew Li is requesting for someone to meet with him to go over the Life-studies module.

_______________________________________________________________________________________________________________

Priority Key
HP = High Priority
MP = Medium Priority

**Leave slips:**
- [ ] **HP** Approved leave slips are not being reflected on attendance. Example: See Andrew Jen's attendance and leave slips (2257, 2258, 2259) for 3/11. May be due to other leave slips being previously denied for that same roll call. @billyeh ?

- [ ] **HP** TA's are unable to change the events on a pending leave slip this should be editable for them @joeyu23 

- [ ] **MP** Date of last meal out or night out not showing on detailed leave slip view.

- [ ] On the TA view, under TA informed, leave slip does not default to blank. Right now, the field defaults to the name of the TA assigned.

- [ ] TA view: Need functionality to filter leave slips by trainee first.

- [ ] Show leave slip IDs on list and detailed leave slip views.

- Assigned TA 
  - [x] Filter out Saturday TAs @davidhtien https://github.com/attendanceproject/djattendance/pull/949

- TA sisters
  - [ ] Transfer and approve button (automatically transfers to linked TA brother)
  - [ ] Save button (allows TA sister to make edits to leave slips, including TA informed)
  - [ ] Transfer button (allows TA sisters to transfer to linked TA brother without approving it)

- [ ] **HP** Change list view so that we can approve multiple leave slips without the lag of the screen being refreshed. @iamsitting @davidhtien 

- [ ] **MP** Leave slips default to "Yes, TA informed" with the name of a TA. This results in many inaccurate leave slips. The default should be blank and the trainee should be required to make an input.

- [ ] **HP** TA sisters' transfer process should not approve leave slips by default.

- [ ] **MP** TAs unable to see all the different fields on a night out leave slip on detailed page. Would need to change identiy to the trainee. @bdou 

- [x] **HP** Trainees unable to see TA comments on leave slips.

- [ ] **MP** There is an inherent issue with how roll and leave slip entries are being shown on the detailed leave slip page. There is no way to tell visually if there is an absence or tardy "under" a leave slip. Right now any approved leave slip changes the color of the event to blue, whether there is anything marked under or not. Please follow the principle of what we had in the old attendance server 

- [ ] **MP** Unable to transfer group leave slips.

- [ ] **MP** Numerous night out leave slips being reported as disappearing or moving to the following week on its own. Example: Connor Robinson, Samuel Gutierrez, Nestor Zepeda.

- [ ] TA informed for a trainee is by default their linked TA. However, there is a request for this default to be blank since it is possible for this to result in inaccurate leave slips
 
- [ ] TA leave slip detailed view on the detailed view, change fields to Trainee, Reason, Description, TA Comments, TA Informed, TA Assigned, and Private TA Comments.

- [ ] On the detailed view, if a trainee says that he did not inform the office, the text only says "No", as opposed to "Training office informed? Yes". Example: http://10.0.8.35/leaveslips/individual/update/1646

- [ ] Either trainees are able to submit leave slips saying that they informed the office but not say who they informed, OR there is
something wrong with the TA informed name not showing. Example: http://10.0.8.35/leaveslips/individual/update/1517. If they mark
informed they should be forced to select a TA informed

- [ ] Meal cleanup leave slips also excusing trainees from the meals themselves. Not an issue with the start time of the leave slip.

- [ ] Multiple tabs popping up when opening detailed pages for leave slips. Should go straight into the page in the same tab

- [x] The leave slip submission acknowledgement disappears too quickly @finben

- [ ] Allow trainees to access previous Leave slips. Maybe a ListView for trainees.

**Extra field:**
  - [ ] “Does not affect perfect attendance” (Automatic for Conferences, team trips, house meals, service, fellowship, and allow for TA override)

- [ ] Add functionality to "sign out" of Monday dinner via leave slip.

**GROUP LEAVE SLIPS**

- [ ] When opening up a group leave slip, no roll events are highlighted on a trainee's personal schedule. This causes confusion, since roll events ARE highlighted on personal leave slips, plus the inability to edit a group leave slip.

- [ ] Unable to tell who originally submitted a group leave slip.

**GRADUATION**

- [x] For Considerations sub-page, take off question 3. Match exact wording of the questions from the old attendance server. May need functionality to be able to edit the questions and for a TA to see what the trainee sees. @finben

**ROLLS:**
- [ ] Add force page when submitting attendance late. @iamsitting 

- [ ] House and Team Roll (make a dummy save, and finalize button) @priscilagonzalez 

- [ ] Need unfinalize roll button

**BIBLE READING TRACKER**
- [ ] We no longer need a notification saying trainee has not finalized Bible reading since this is an impossibility with the force page @yipingbenjaminliu 

- [ ] Trainee has a "bell" (not pop-up) notification to finalize Bible reading for a prior week. Save button is not grayed out, but finalize button is grayed out. See Week 3 of Carrie Chambers Bible reading tracker.

**Web Access Requests:**
- [x] For TAs: order by status (Pending, Fellowship, Approved, Denied) then by submission date @iamsitting #870 

- [ ] Approving a web access request leads to a blank page.

- [ ] Urgent text should be red @bdou 

**ROOM RESERVATIONS:**

- [ ] Rooms are not in alphabetical order after editing available rooms

- [ ] Marking a request for fellowship removes the request from the list. You have to remove "pending" from the search box and type in "fellowship" or "marked for fellowship". This is too cumbersome and confusing. The list should not be based on a search for "pending". Are there any other modules set up like this?

- [ ] Schedule needs to be imported into the new attendance server

- [ ] Room choices are not in alphabetical order after editing available rooms.

- [ ] Updating/editing a trainee's room reservation request approves it

**TA Landing Page**
- [ ] TA's should see their personal number of items as well as a total number of items. Ex. web access requests 5 (390). The only exception is leave slips which should only show the TA's personal number of slips @samvictor232 

- [x] "Marked for Fellowship" link to leave slips on TA homepage brings us to the same page as pending leave slips. 9fe0fb8

**TA List Views**
- [ ] Get rid of comment button from TA announcement list view for consistency across site.

- [ ] The order of the leave slips on the list view does not make sense. Are they being ordered by when the leave slip was submitted? If so, they should be ordered by date and event instead, starting with the earliest.

- [ ] TA is able to delete a leave slip from the trainee's personal attendance, however, it still appears on the TA leave slip list.

- [ ] On the summary page ("View Trainee Attendance"), the submitted column on the left is extremely confusing. I thought for the longest time it was referring to the event. Please remove it; we do not need to see that information there. It would be more useful if it indicated the date of the event.

- [ ] **MP** On the leave slips summary list page, any filters we ask for are lost and default after we process a single leave slip. The filters should be kept @jontey 

- [ ] All TA list views need the following sort order (Pending, Marked for Fellowship, Approve, Deny) to stop them from having to excessively scroll. Secondary sort needs to be time submitted based

- [ ] For Leave Slip TA list view Add attendance period column on list view.

- [ ] "View leave slips for" on list view includes people who are not TAs.

- [ ] Trainee names need to be made more visible (increase font size)

- [ ] Across site lists need delete options for items from TA list view

- [ ] "Texted attendance number" notation on list view should be capitalized for consistency.

**ABSENTEE TRAINEE ROSTER**

**ANNOUNCEMENTS**
- [ ] Would it be possible for the trainees names to still appear on the announcement even after they've read it? Currently the name disappears from the announcement after they "mark as read". On the old server it would appear in italics.

**LIFE STUDIES**

- [ ] When trying to mark a Life-study summary that is manually entered, nothing happens.

- [ ] For the “Assign Discipline” function for attendance, it would be helpful to have more details of what time the periods are covered, etc.

- [ ] **MP** There does not seem to be a way to assign discipline based on attendance.

**REPORTS**

- [ ] The reports generated and printable for Life-study assignments is incorrect. Andrew Li is requesting for someone to meet with him to go over the Life-studies module. @finben will meet with Andrew then work with @yipingbenjaminliu

**Other:**

- [ ] First-year trainees should not be able to stream audio from second-year classes.

- [x] **HP** FTTA-XB application is need @ryanli633 #881 

- [ ] **MP** HC Survey TA's are looking for a way to edit what the survey asks, edit times, and delete the server

- [ ] **MP** Trainees with designated services need to input their service hours. #868 

- [ ] **MP**Button to change attendance period is only one-pixel large on Firefox. Also not intuitive.

- [ ] Add dishware requests to linens since they are taken care of by the same service team

- [ ] House Requests, Room Reservations, Life Studies, Class notes, are user (Trainee or TA) specific.

- [ ] **MP** Trainees with designated services need to be able to input their service hours (ex Greg Lee Transportation) #868 

- [ ] Have a way to take attendance and assign discipline for missed services, rotational or designated.

- [ ] Too many trainees can submit linens requests. @ruthnan 

- [ ] TAs need to be able to submit new personal or group leave slips on behalf of trainees.

-----------------------------------
COMPLETED

Announcements: eb42242506ed2c1933c171d1184fa4014efe3820
-  [x] Auto-approve announce request for TAs (Hide status field for TAs)

- [x] Bug: Submitted by “None” when it’s submitted by a TA

- [x] In TA list view the submitted by includes trainee email inconsistent with other list views. Email not needed

- [x] fix switch identity page trainee selector

-Leave Slips
- [x] **HP** Unable to view processed leave slips.

- [x] Allow all leave slip fields to be edited by TA @iamsitting 0768dae38a1cadac66e1d0fd464c8da2aa65b27e

- [x] Better feedback for Leave Slip submission. (@davidhtien) 2e43ec1 
@billyeh , maybe make something similar to what bible_tracker does right now, flash a save. take a look at https://github.com/attendanceproject/djattendance/blob/eaa38a736f934c3a2e9e23db18c3176f8bc65ab6/ap/bible_tracker/templates/bible_tracker/index.html#L480-L482
https://github.com/attendanceproject/djattendance/blob/eaa38a736f934c3a2e9e23db18c3176f8bc65ab6/ap/bible_tracker/templates/bible_tracker/index.html#L271-L272

- [x] After approving leave slip, redirect to next pending leave slip 8b1ec8ceca41635aae918984ed5cdc62bf23b798

- [x] TA informed should be a field that doesn’t affect where the leave slip goes 0768dae38a1cadac66e1d0fd464c8da2aa65b27e

- Assigned TA
  - [x] should be trainee’s default TA or transferred TA (Trainees don’t see this) @billyeh 5601e08
  - [x] Leave slip count is wrong on TA landing page 1bb420f52ee0c27480ad6ac2e521199da1a6741f

-Extra Field
- [x] Hover over event for start time, event name, and reason 5119ce9

- [x] Color code Leave Slips status codes on personal attendance @bdou

- [x] Need more obvious event highlighting when editing/reviewing leave slips 94b37d7f0e319cd962c02ca21248fa59a54c94a8

- [x] Show submission date on leave slip detail @samvictor232 76354fa900280d7268a56cdb02a5b55fe60ad1bc

- [x] Add “last slip” to meal/night out, even if there isn’t one on record 652eb48bc

- [x] On ListView, Month abbreviations are not consistent @samvictor232 50d2da0c62eea24157c3a2b4661322f572a72864

- [x] Group slip approve/fellowship/deny buttons need to be bigger @samvictor232

- [x] Trainees should be able to edit their own leave slips as long as the leave slip is still in pending status

-Rolls
- [x] Implement way for 2nd years on first attendance

- [x] Team Roll is not auto-saving

- [x] 2nd year rolls finalize button has vague feedback

- [x] TA needs permission to submit rolls 7a31214191df594c151d1a89182b574fe8f558ea

Trainee items:
- [x] Allow trainees to see linens requests for trainees. fbc394c

Life-studies:
- [x] Search function for Life Study ListView 7a8dd6d9cf5475a5ce2cc13d6ff5167300cc63d0

- [x] Populate with life-study books

- [x] Decrease Life Study Penalty ce0a11e

Web Access Requests:
- [x] **MP** Bug: Mark for fellowship actually approves @iamsitting (works for me)

- [x] Urgent value is not shown for nonurgent request detail views @bdou 

- [x] Seeing web access requests submitted by "none" (e.g., http://10.0.8.35/web_access/detail/384).

TA Landing Page:
- [x] Remove housing from TA landing page as they do not need this 0815c9b

Other:
- [x] Graduation module needing DVD numbers, grad invites, and remembrance pages @yipingbenjaminliu 58bb827

- [x] Maintenance request brothers want a csv export to fit their current workflow af830b88b54425eb076f51eeaf04b2ae442e3592

Room Reservations:
- [x] Requests do not match landing page count c83dad736cb418fae0d8161eee6eb2d1a867ad62

- [x] When editing a room reservation request, the title page is "FTTA | Room Reservation", but on other pages it is pluralized.

- [x] Page title of http://10.0.8.35/audio/ta-list/ is not entirely capitalized @finben

Absentee Trainee Roster:
- [x] Change "Everyone is Present!" text to "All Present" @yipingbenjaminliu dcca3503210217bf453a257d603efaf5c2fdc274

- [x] Absent Trainee Roster is not needed on Monday (related: # days on report should not reset after Monday) 4601138180c00912a5c41378b850fac9762f1659

- [x] Change Email account name to something better than “AP Server” d650605f2

- [x] Remove "Coming to Class" as an option 71be9bb48d346f84f24e102a2839a3493d330154

Attendance:
- [x] Allow TAs to change self-attendance field for 2nd year trainees 0da336236ef01c9087cb4140395d84f9e8bc4fab

**Comment by finben** [comment]
Closing out. Please begin to use the most updated list issue #959
