### ISSUE TITLE
Feedback Update 3/31/18

### ISSUE THREAD

**Issue by finben** [attendanceproject/djattendance#959]
**Super Critical Issues:** 
These are Highest Priority issues (On the TA spreadsheet, they're colored magenta)

- [ ] Fix assign discipline based on attendance @iamsitting

- [ ] Trainees unable to see TA comments on leave slips if the TA does not hit save before either approving, denying, or marking for fellowship. This should not be the case as it does not flow with TA workflow as they are going through leave slips. @joeyu23 

- [ ] TAs unable to edit group leave slips @joeyu23

- [ ] Program TA brother/TA sister pairs for TA sister leave slip transfer process. Use the pairings from the old attendance server. #990

- [ ] Approved leave slips are not being reflected on attendance if there was a previously denied leave slip for that event. Example: See Andrew Jen's attendance and leave slips (2257, 2258, 2259) for 3/11. 

- [x] Ensure graduation module is complete. Should have FTTA-XB Application, Graduation DVD, Graduation Invitations, Fourth Term
Considerations, Graduation Program Remembrances, Testimony, and Graduation Program Outline Burden, with respective report pages for
each. Missing at least four sub-pages. @yipingbenjaminliu #881, #963, #964, #965, #966, etc.

- [ ] The reports generated and printable for Life-study assignments is incorrect. May need to meet with Andrew Li

______________________________________________________________________________________________________________________________________________________________________

Priority Key
HP = High Priority
MP = Medium Priority

**Leave slips:**
- [x] **HP** Approved leave slips are not being reflected on attendance. Example: See Andrew Jen's attendance and leave slips (2257, 2258, 2259) for 3/11. May be due to other leave slips being previously denied for that same roll call. @billyeh ?

- [ ] **HP** TA's are unable to change the events on a pending leave slip this should be editable for them @joeyu23 

- [ ] **MP** Date of last meal out or night out not showing on detailed leave slip view.

- [ ] TA view: Need functionality to filter leave slips by trainee first.

- [ ] Show leave slip IDs on list and detailed leave slip views. d08e785a80ca46be8eb50d4dc46d34bff1e0fdcb

- TA sisters
  - [ ] Transfer and approve button (automatically transfers to linked TA brother)
  - [ ] Save button (allows TA sister to make edits to leave slips, including TA informed)
  - [ ] Transfer button (allows TA sisters to transfer to linked TA brother without approving it)

- [ ] **HP** Change list view so that we can approve multiple leave slips without the lag of the screen being refreshed. @iamsitting @davidhtien 

- [ ] **MP** TAs unable to see all the different fields on a night out leave slip on detailed page. Would need to change identiy to the trainee. @bdou 

- [ ] **MP** There is an inherent issue with how roll and leave slip entries are being shown on the detailed leave slip page. There is no way to tell visually if there is an absence or tardy "under" a leave slip. Right now any approved leave slip changes the color of the event to blue, whether there is anything marked under or not. Please follow the principle of what we had in the old attendance server 

- [ ] **MP** Unable to transfer group leave slips.

- [ ] **MP** Numerous night out leave slips being reported as disappearing or moving to the following week on its own. Example: Connor Robinson, Samuel Gutierrez, Nestor Zepeda.

- [ ] TA informed for a trainee is by default their linked TA. However, there is a request for this default to be blank since it is possible for this to result in inaccurate leave slips
 
- [ ] TA leave slip detailed view on the detailed view, change fields to Trainee, Reason, Description, TA Comments, TA Informed, TA Assigned, and Private TA Comments.

- [ ] On the detailed view, if a trainee says that he did not inform the office, the text only says "No", as opposed to "Training office informed? Yes". Example: http://10.0.8.35/leaveslips/individual/update/1646

- [ ] Meal cleanup leave slips also excusing trainees from the meals themselves. Not an issue with the start time of the leave slip.

- [ ] Multiple tabs popping up when opening detailed pages for leave slips. Should go straight into the page in the same tab

- [ ] Allow trainees to access previous Leave slips. Maybe a ListView for trainees.

**Extra field:**
  - [ ] “Does not affect perfect attendance” (Automatic for Conferences, team trips, house meals, service, fellowship, and allow for TA override)

- [ ] Add functionality to "sign out" of Monday dinner via leave slip.

**GROUP LEAVE SLIPS**

- [ ] When opening up a group leave slip, no roll events are highlighted on a trainee's personal schedule. This causes confusion, since roll events ARE highlighted on personal leave slips, plus the inability to edit a group leave slip.

- [ ] Unable to tell who originally submitted a group leave slip.

**GRADUATION**

**ROLLS:**
- [ ] Add force page when submitting attendance late. @iamsitting 

- [ ] House and Team Roll (make a dummy save, and finalize button) @priscilagonzalez 

- [ ] Need unfinalize roll button

- [ ] TAs do not have a way to input team and house attendance. We currently have to go to each individual trainee.

**BIBLE READING TRACKER**
- [x] We no longer need a notification saying trainee has not finalized Bible reading since this is an impossibility with the force page @yipingbenjaminliu 

- [x] Trainee has a "bell" (not pop-up) notification to finalize Bible reading for a prior week. Save button is not grayed out, but finalize button is grayed out. See Week 3 of Carrie Chambers Bible reading tracker.

**Web Access Requests:**

- [ ] Approving a web access request leads to a blank page.

- [ ] No buttons to process a web access request after requesting fellowship @ruthnan 

- [ ] Urgent text should be red @bdou 

**ROOM RESERVATIONS:**

- [ ] Rooms are not in alphabetical order after editing available rooms

- [ ] Marking a request for fellowship removes the request from the list. You have to remove "pending" from the search box and type in "fellowship" or "marked for fellowship". This is too cumbersome and confusing. The list should not be based on a search for "pending". Are there any other modules set up like this?

- [ ] Schedule needs to be imported into the new attendance server

- [ ] Room choices are not in alphabetical order after editing available rooms.

- [ ] Updating/editing a trainee's room reservation request approves it

**TA Landing Page**
- [ ] TA's should see their personal number of items as well as a total number of items. Ex. web access requests 5 (390). The only exception is leave slips which should only show the TA's personal number of slips @samvictor232 

**TA List Views**
- [ ] Get rid of comment button from TA announcement list view for consistency across site.

- [ ] The order of the leave slips on the list view does not make sense. Are they being ordered by when the leave slip was submitted? If so, they should be ordered by date and event instead, starting with the earliest.

- [ ] TA is able to delete a leave slip from the trainee's personal attendance, however, it still appears on the TA leave slip list.

- [ ] On the summary page ("View Trainee Attendance"), the submitted column on the left is extremely confusing. I thought for the longest time it was referring to the event. Please remove it; we do not need to see that information there. It would be more useful if it indicated the date of the event.

- [ ] **MP** On the leave slips summary list page, any filters we ask for are lost and default after we process a single leave slip. The filters should be kept @jontey 

- [ ] All TA list views need the following sort order (Pending, Marked for Fellowship, Approve, Deny) to stop them from having to excessively scroll. Secondary sort needs to be time submitted based

- [ ] For Leave Slip TA list view Add attendance period column on list view.

- [ ] "View leave slips for" on list view includes people who are not TAs.

- [ ] Trainee names need to be made more visible (increase font size) @finben

- [ ] Across site lists need delete options for items from TA list view

- [ ] "Texted attendance number" notation on list view should be capitalized for consistency. @finben

**ANNOUNCEMENTS**
- [ ] Would it be possible for the trainees names to still appear on the announcement even after they've read it? Currently the name disappears from the announcement after they "mark as read". On the old server it would appear in italics.

**ABSENTEE TRAINEE ROSTER**
- [ ] Pluses are not being noted on the absent trainee roster. Pluses indicate that there is a possibility the trainee has been absent for more days, but cannot be confirmed due to HCs not submitting a daily accountability form

- [ ] Need a way to show which houses actually submitted the HC survey and which houses did not. Currently, if the HCs do not open the page, they do not show up on the report page, and if the HCs open the survey page, it will list them on the report page even without submitting the survey.

**LIFE STUDIES**

- [ ] When trying to mark a Life-study summary that is manually entered, nothing happens.

- [x] For the “Assign Discipline” function for attendance, it would be helpful to have more details of what time the periods are covered, etc. @iamsitting - You can choose which period to assign discipline for.

**REPORTS**

- [ ] The reports generated and printable for Life-study assignments is incorrect. Andrew Li is requesting for someone to meet with him to go over the Life-studies module. @finben will meet with Andrew then work with @yipingbenjaminliu

**Other:**

- [ ] First-year trainees should not be able to stream audio from second-year classes. @ruthnan #894 59f561c

- [ ] **MP** HC Survey TA's are looking for a way to edit what the survey asks, edit times, and delete the server

- [x] **MP** Trainees with designated services need to input their service hours. #868 

- [ ] **MP**Button to change attendance period is only one-pixel large on Firefox. Also not intuitive.

- [ ] Add dishware requests to linens since they are taken care of by the same service team

- [ ] House Requests, Room Reservations, Life Studies, Class notes, are user (Trainee or TA) specific.

- [ ] **MP** Trainees with designated services need to be able to input their service hours (ex Greg Lee Transportation) #868 

- [ ] Have a way to take attendance and assign discipline for missed services, rotational or designated.

- [ ] Too many trainees can submit linens requests. @ruthnan 

- [ ] TAs need to be able to submit new personal or group leave slips on behalf of trainees.

---------------------
**COMPLETED**
---------------------

**Leave Slips**
- [ ] Fix TA sisters' transfer process. TA sisters' transfer process should not approve leave slips by default. @davidhtien: we can't reproduce this behavior, need more details or an example

- [x] **HP** Trainees unable to see TA comments on leave slips.

- [ x ] Either trainees are able to submit leave slips saying that they informed the office but not say who they informed, OR there is
something wrong with the TA informed name not showing. Example: http://10.0.8.35/leaveslips/individual/update/1517. If they mark
informed they should be forced to select a TA informed  (finben "I am unable to reproduce and am marking this as solved)

- Assigned TA 
  - [x] Filter out Saturday TAs @davidhtien https://github.com/attendanceproject/djattendance/pull/949

**Web Access Requests:**
- [x] For TAs: order by status (Pending, Fellowship, Approved, Denied) then by submission date @iamsitting #870 

**Graduation**
- [x] For Considerations sub-page, take off question 3. Match exact wording of the questions from the old attendance server. May need functionality to be able to edit the questions and for a TA to see what the trainee sees. @finben

**MISC**
- [x] **HP** FTTA-XB application is need @ryanli633 #881 

- [x] "Marked for Fellowship" link to leave slips on TA homepage brings us to the same page as pending leave slips. @samvictor232 

- [x] The leave slip submission acknowledgement disappears too quickly @finben
