### ISSUE TITLE
Feedback 4/7/18

### ISSUE THREAD

**Issue by JoannaRumbley** [attendanceproject/djattendance#994]
**Super Critical Issues:** 
These are Highest Priority issues (On the TA spreadsheet, they're colored magenta)

- [ ] **Leave slips:** Fix assign discipline based on attendance @iamsitting

- [x] **Leave slips:** Trainees unable to see TA comments on leave slips if the TA does not hit save before either approving, denying, or marking for fellowship. This should not be the case as it does not flow with TA workflow as they are going through leave slips. @joeyu23 

- [ ] **Leave slips:** TAs unable to edit group leave slips @joeyu23

- [x] **Leave slips:** TA Sister approved should not be a slip status @davidhtien (talk with Bill; he was assigned to this before) #1014 

- [ ] **Reports:** The reports generated and printable for Life-study assignments is incorrect. Andrew Li is requesting for someone to meet with him to go over the Life-studies module. @finben will meet with Andrew then work with @yipingbenjaminliu

______________________________________________________________________________________________________________________________________________________________________

Priority Key
HP = High Priority
MP = Medium Priority

**Leave slips:**
- [ ] **HP** TA's are unable to change the events on a pending leave slip this should be editable for them @joeyu23 (They cannot change events on group slips. Else, everything is good)

- [ ] **MP** Date of last meal out or night out not showing on detailed leave slip view. @yipingbenjaminliu 

- [x] **HP** TA view: Need functionality to filter leave slips by trainee first. @iamsitting #1014 

- [x] Show leave slip IDs on list and detailed leave slip views. d08e785a80ca46be8eb50d4dc46d34bff1e0fdcb

- [x] **MP** Leave slip submission acknowledgement disappearing too quickly was "solved," but now there are 2 popups when a TA clicks on approve/deny/edit, etc. button. One says "Saved" and another says for example, "Ray Ding's personal slip was Approved." Probably best to only have the 2nd pop up for 1-2 secs, then make it disappear and move to the next pending leaveslip. #1010 

- TA sisters @davidhtien
  - [x] Transfer and approve button (automatically transfers to linked TA brother)
  - [x] Save button (allows TA sister to make edits to leave slips, including TA informed)
  - [x] Transfer button (allows TA sisters to transfer to linked TA brother without approving it)

- [x] **HP** Change list view so that we can approve multiple leave slips without the lag of the screen being refreshed. @iamsitting @davidhtien #1018 

- [ ] **MP** There is an inherent issue with how roll and leave slip entries are being shown on the detailed leave slip page. There is no way to tell visually if there is an absence or tardy "under" a leave slip. Right now any approved leave slip changes the color of the event to blue, whether there is anything marked under or not. Please follow the principle of what we had in the old attendance server 

- [ ] **MP** Numerous night out leave slips being reported as disappearing or moving to the following week on its own. Example: Connor Robinson, Samuel Gutierrez, Nestor Zepeda.

- [ ] TA informed for a trainee is by default their linked TA. However, there is a request for this default to be blank since it is possible for this to result in inaccurate leave slips
 
- [ ] TA leave slip detailed view on the detailed view, change fields to Trainee, Reason, Description, TA Comments, TA Informed, TA Assigned, and Private TA Comments.

- [x] On the leave slips summary list page, "Filter by status:" should be on the next line. @finben ba7e67edddb0bf7efe68bdc8c962df05a5ec58ba

- [ ] On the detailed view, if a trainee says that he did not inform the office, the text only says "No", as opposed to "Training office informed? Yes". Example: http://10.0.8.35/leaveslips/individual/update/1646

- [ ] Meal cleanup leave slips also excusing trainees from the meals themselves. Not an issue with the start time of the leave slip.

- [ ] Allow trainees to access previous Leave slips. Maybe a ListView for trainees.

**Extra field:**
  - [ ] “Does not affect perfect attendance” (Automatic for Conferences, team trips, house meals, service, fellowship, and allow for TA override)

- [ ] Add functionality to "sign out" of Monday dinner via leave slip.

**GROUP LEAVE SLIPS**

- [ ] When opening up a group leave slip, no roll events are highlighted on a trainee's personal schedule. This causes confusion, since roll events ARE highlighted on personal leave slips, plus the inability to edit a group leave slip.

- [ ] Unable to tell who originally submitted a group leave slip. @finben 

**ROLLS:**
- [ ] Add force page when submitting attendance late. @iamsitting 

- [ ] House and Team Roll (make a dummy save, and finalize button) @priscilagonzalez 

- [ ] Need unfinalize roll button

- [ ] TAs do not have a way to input team and house attendance. We currently have to go to each individual trainee.

**Web Access Requests:**

- [ ] No buttons to process a web access request after requesting fellowship @ruthnan 

- [ ] Urgent text should be red @bdou 

**ROOM RESERVATIONS:**

- [ ] Rooms are not in alphabetical order after editing available rooms

- [ ] Marking a request for fellowship removes the request from the list. You have to remove "pending" from the search box and type in "fellowship" or "marked for fellowship". This is too cumbersome and confusing. The list should not be based on a search for "pending". Are there any other modules set up like this?

- [ ] Room choices are not in alphabetical order after editing available rooms.

- [ ] Updating/editing a trainee's room reservation request approves it

**TA Landing Page**
- [ ] TA's should see their personal number of items as well as a total number of items. Ex. web access requests 5 (390). The only exception is leave slips which should only show the TA's personal number of slips @samvictor232 

**TA List Views**

- [x] The order of the leave slips on the list view does not make sense. Are they being ordered by when the leave slip was submitted? If so, they should be ordered by date and event instead, starting with the earliest. -- It's by submission date @iamsitting

- [ ] TA is able to delete a leave slip from the trainee's personal attendance, however, it still appears on the TA leave slip list.

- [ ] On the summary page ("View Trainee Attendance"), the submitted column on the left is extremely confusing. I thought for the longest time it was referring to the event. Please remove it; we do not need to see that information there. It would be more useful if it indicated the date of the event.

- [ ] **MP** On the leave slips summary list page, any filters we ask for are lost and default after we process a single leave slip. The filters should be kept @jontey 

- [ ] All TA list views need the following sort order (Pending, Marked for Fellowship, Approve, Deny) to stop them from having to excessively scroll. Secondary sort needs to be time submitted based

- [ ] For Leave Slip TA list view Add attendance period column on list view.

- [ ] "View leave slips for" on list view includes people who are not TAs.

- [ ] Across site lists need delete options for items from TA list view

**ANNOUNCEMENTS**
- [ ] Would it be possible for the trainees names to still appear on the announcement even after they've read it? Currently the name disappears from the announcement after they "mark as read". On the old server it would appear in italics. @finben

**ABSENTEE TRAINEE ROSTER**
- [ ] Pluses are not being noted on the absent trainee roster. Pluses indicate that there is a possibility the trainee has been absent for more days, but cannot be confirmed due to HCs not submitting a daily accountability form

- [ ] Need a way to show which houses actually submitted the HC survey and which houses did not. Currently, if the HCs do not open the page, they do not show up on the report page, and if the HCs open the survey page, it will list them on the report page even without submitting the survey.

**LIFE STUDIES**

- [ ] For the “Assign Discipline” function for attendance the dates along with the period nees to be shown

**REPORTS**

- [ ] **MP** Generate grade and attendance reports by gospel team and sending locality.

**ACCOUNTS**

- [ ] **MP** Saturday helper brothers cannot approve web access requests. May affect other modules.

**BIBLE READING TRACKER**

- [ ] Trainees can finalize their Bible reading without making inputs for all of the days. Example: Mark Fan week 6 /JR - Also see related issue #1011 @berlyseria 

**Other:**

- [ ] **MP** HC Survey TA's are looking for a way to edit what the survey asks, edit times, and delete the server

- [ ] **MP**Button to change attendance period is only one-pixel large on Firefox. Also not intuitive.

- [ ] House Requests, Room Reservations, Life Studies, Class notes, are user (Trainee or TA) specific.

- [ ] Have a way to take attendance and assign discipline for missed services, rotational or designated.

- [ ] Too many trainees can submit linens requests. @ruthnan 

- [ ] TAs need to be able to submit new personal or group leave slips on behalf of trainees.

- [ ] **HP** Ensure class notes report page is working after resolving roll/leaveslip issue

- [ ] No organization on HC survey report. Should list all the houses by brothers then sisters. Also, couples do not need to submit surveys, so they should be removed from inputting and the reports.

- [ ] 504 Gateway Time-out error when trying to pull up all leave slips for all TAs, even when limiting to 25 slips per page

---------------------
**COMPLETED**
---------------------
**LEAVE SLIPS**

- [x] **MP** TAs unable to see all the different fields on a night out leave slip on detailed page. Would need to change identiy to the trainee. @bdou 

- [x] Trainee names need to be made more visible (increase font size) @finben

- [x] **MP** Unable to transfer group leave slips. "Ben F - marking this off. It works I have tested. They just need to change the TA and save"

**BIBLE READING TRACKER**

- [x] Trainee has a "bell" (not pop-up) notification to finalize Bible reading for a prior week. Save button is not grayed out, but finalize button is grayed out. See Week 3 of Carrie Chambers Bible reading tracker.

**MISC**

- [x] **MP** Trainees with designated services need to be able to input their service hours (ex Greg Lee Transportation) #868 

- [x] Schedule needs to be imported into the new attendance server "benf - I am marking this off. We discussed that we are not going to do this this term with Jerome. He is going to continue managing with both servers for rest of term"

- [x] **Leave slips:** Program TA brother/TA sister pairs for TA sister leave slip transfer process. Use the pairings from the old attendance server. #990

- [x] When trying to mark a Life-study summary that is manually entered, nothing happens. @finben #1019

**Comment by JoannaRumbley** [comment]
@iamsitting Ok, thanks. Will this page still take a long time after solving the rolls problem? 
I changed the issue to a HP item, to make sure it is efficient/quick enough to use after solving the rolls issue related to it: 
**HP** Ensure class notes report page is working after resolving roll/leaveslip issue

**Comment by JoannaRumbley** [comment]
#959

**Comment by finben** [comment]
Closing out after a successful amount of work being done ITERO. Issues are moving to #1053 please work from updated list
